SignalK/signalk-server

CONSUMERS.md, examples/consumer-example.html, lib/config/development.js
* add minimal browser consumer & examples directory
* add mapping to serve the examples dir
* update consumers doc: remove old sample code, add pointers to new one, add instructions to install consumers with bower
Now that I think of this it turned pretty introverted: node server specific and the consumers are the ones that I wrote. Feel free to add other viewpoints.
Closes #18.
=> Update consumer getting started 

lib/interfaces/ws.js, package.json
=> Fix path subscription

lib/index.js, lib/interfaces/index.js, settings/aava-file-settings.json, settings/actisense-serial-settings.json, settings/commandline-provider-settings.json, settings/volare-file-settings.json, settings/volare-gpsd-settings.json
with the option  of disabling interfaces by configuration.
=> Change interfaces default policy to load all interfaces

README.md
I noticed the endpoints are incorrect so I updated them.
=> update rest api and streaming endpoints in readme

bin/actisense-serial-n2kd, bin/n2k-from-actisense, bin/n2k-from-file, bin/nmea-from-file
Did this work?  trying to create a pull request for updates to the startup scripts.
=> make startup scripts more shell agnostic

.gitignore, README.md, bin/ssl-n2k-from-file, lib/index.js, package.json, settings/aava-ssl-file-settings.json
=> Add ssl support

lib/interfaces/nmea-tcp.js, lib/pipedproviders.js, providers/nmea0183-signalk.js
Add a tcp server that allows you to stream any nmea0183 events emitted from the providerpipe elements over TCP.
=> Add nmea0183 over TCP

lib/interfaces/rest.js, lib/interfaces/ws.js, lib/mdns.js
=> Correctly advertise TLS in mDNS metadata

lib/config/config.js, lib/interfaces/ws.js
https://github.com/SignalK/signalk.github.io/pull/29
=> Implement the standard subscribe url parameters

lib/index.js, lib/interfaces/rest.js, providers/tcp.js, settings/volare-tcp-settings.json
=> Various changes to the reconnect strategy of TCP provider

raspberry_pi_installation.md, rpi-setup.sh
Script added that generates UUID as requested in #58 and sets up a systemd service for raspberry pis.
=> Setup script for raspberry pi

lib/interfaces/nmea-tcp.js, lib/interfaces/tcp.js, package.json
=> Econnreset thefix

lib/index.js
In case certificate creation/saving the certificate does not
succeed fail with error message.
=> Handle error in certificate creation

lib/interfaces/ws.js
Start accepting deltas through the regular WebSocket connection.
=> Accept deltas via WebSocket connection

plugin-config/webpack.config.js
Use React's production build in building the configuration
mini-application.
=> Build config React app with production React

README.md, SERVERPLUGINS.md, lib/interfaces/tcp.js, lib/mdns.js, package.json, providers/log.js
Newer winston does not include DailyRotateFile, you need to require it separately from a separate module.
=> Fix winston in log.js provider

package.json
Closes #148
https://greenkeeper.io/
=> fix(package): update ws to version 2.0.3

raspberry_pi_installation.md
@tkurki As agreed I have updated the installation so i matches "reality" ;-) and also added Samba install, which I think really helps us newbies.
=> Update of the installation

providers/liner.js
Logging is achieved with the Log provider pipeline element,
which has this same functionality, plus multiplexing.
=> Remove logging in liner

rpi-setup.sh
Issue a message and exit if not
=> Check if rpi-setup is run as root

lib/interfaces/charts.js, package.json
Add support for charts in mbtiles format.
=> Mbtiles charts

package.json
This reflects commit history & current activity.
=> chore: update author & collaborators

README.md, SERVERPLUGINS.md, WEBAPPS.md
=> Update documentation on apps, plugins and app store

rpi-setup.sh
=> Change server startup user

lib/interfaces/plugins.js
Add the option for the schema to be a function so that the schema can be generated on the fly based on dynamic data.
=> feature:dynamic plugin schema

package.json
=> fix(package): update @signalk/signalk-schema to version 0.0.1-10

Dockerfile, README.md
Add Dockerfile that you can use to install & run Signal K
Node Server in a Docker container.
=> feature: add Dockerfile

providers/tcp.js
=> Fix typo in providers/tcp.js

lib/index.js, rpi-setup.sh
This addresses #352 and also fixes a bug in the redirect code when running from systemd
=> fix: update rpi-setup.sh to support ssl config and dual http+https

lib/interfaces/rest.js, lib/interfaces/ws.js, test/subscriptions.js
https://github.com/SignalK/specification/issues/391
Replaces #332
=> fix: make /self relative to root

package.json
=> fix(package): update @signalk/n2k-signalk to version 1.0.1

package.json
=> fix(package): update @signalk/signalk-schema to version 1.0.2

README.md
Update installation instructions to reflect npm installation.
=> doc: update installation instructions

.gitignore, SERVERPLUGINS.md, lib/interfaces/plugins.js, package.json, providers/execute.js, test/plugin-test-config/defaults.json, test/plugin-test-config/node_modules/testplugin/index.js, test/plugin-test-config/node_modules/testplugin/package.json, test/plugin-test-config/package.json, test/plugin-test-config/plugin-config-data/testplugin.json, test/plugins.js, test/ssl.js
Start creating a proper api that plugins can use to access the server's functionality. Update documentation to match the api and current state in general.
=> Plugin api

providers/simple.js
This fixes the missing timestamp sensitive throttling when configuring an N2K file playback from the UI. 
Previously there was just a fixed data rate throttle, that is still in use for NMEA0183 data with no timestamps.
=> Fix: simple provider n2k throttling

raspberry_pi_installation.md
Added how to configure, via Admin UI, real input from NMEA interfaces and the signalk-to-nmea0183 plug in.
=> Update RPi installation guide

SERVERPLUGINS.md, lib/interfaces/plugins.js, plugin-config/src/ConfigurationForm.jsx
App statusMessage() method to plugin interface
to retrieve up to date status of the plugin.
=> feature: plugin.statusMessage()

package.json
=> fix(package): update file-timestamp-stream to version 0.3.0

package.json
=> chore(package): update node-fetch to version 2.1.1

package.json
=> fix(package): update @signalk/n2k-signalk to version 1.2.1

lib/interfaces/ws.js
The userid/name was not being retrieved properly
=> fix: source not getting set correctly for deltas over ws

lib/config/config.js
=> fix: use uuid v4 for uuid generation

bin/signalk-generate-token, package.json
This is needed allow external sources to get a token to send data to the server when security is enabled
=> feature: add ability to generate a security token

providers/serialport.js
Previously there was no limit to how much data would
be written to serialport, which would result in ever growing
buffers and eventual server freeze if the output rate was
more than the serialport could write.
Now there is option maxPendingWrites, which specifies a high
water mark after which input is simply ignored until
the outgoing buffer is below the mark.
This also adds debug statements to debug normal output and
possible overruns.
=> fix: handle serial port buffer overrun

packages/server-admin-ui/README.md, packages/server-admin-ui/src/views/appstore/Apps/AppsList.js
=> doc: add admin ui readme with development instructions

packages/server-admin-ui/package.json, packages/server-admin-ui/src/views/appstore/Apps/AppsList.js
=> feat: Open npm url in new tab. Add link title.

package.json
=> fix(package): update serialport to version 7.0.2

lib/index.js, test/deltacache.js, test/metadata.js, test/subscriptions.js
Either when something goes wrong during server.stop() or when the next test starts before the server stops, the next tests can fail.
=> fix: make server.stop() return a promise so the tests can wait

lib/index.js, lib/pipedproviders.js, providers/mdns-ws.js, providers/simple.js
* reconnect/retry ws connections
* show different connections separately  on the Dashboard
* allow configuration of mdns ws hosts to ignore
=> feature: mdns-ws provider enhancements

lib/config/config.js, lib/interfaces/providers.js, packages/server-admin-ui/src/views/ServerConfig/ProvidersConfiguration.js, test/providers.js
=> fix: prevent adding/updating a provider with an empty or existing id

lib/serverroutes.js
Mistakenly failed to remove code used for testing on my mac
=> fix: server not detecting if running under systemd properly

lib/dummysecurity.js, lib/interfaces/logfiles.js, lib/interfaces/plugins.js, lib/logging.js, packages/server-admin-ui/src/components/Sidebar/Sidebar.js, packages/server-admin-ui/src/containers/Full/Full.js, packages/server-admin-ui/src/views/ServerConfig/Logging.js, providers/log.js
=> feature: add access to log files over http

lib/modules.js
We've either of these have issues with the index not updating.
So this gets results from both and uses the latest version of each module.
=> refactor: search for modules at npmjs.com and npms.io

bin/log2sk, lib/pipedproviders.js
Add a utility to convert multiplexed log file data to SK deltas.
=> feature: add log2sk utility

packages/server-admin-ui/src/views/ServerConfig/Logging.js
Add links to open log files in chartedsails.com if it is available (we are online).
Depends on #652
=> Chartedsails data log links

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js, providers/simple.js
Add the ability to add providers that receive line oriented Signal K delta JSON over serial.
=> Feature: add Signal K JSON over serial support in admin UI

packages/server-admin-ui/package.json
https://nvd.nist.gov/vuln/detail/CVE-2018-14041
=> chore: bootstrap >=4.1.2

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js, providers/simple.js
This replaces #669
difference: fixed Indentation
=> add baudrate to actisense2

lib/streambundle.js
Add accidentally missing this.
=> fix: StreamBundle.getSelfStream

providers/serialport.js
Add retry logic to serialport provider and fix the one-shot
retry that was broken in a732e2eba8f9e319a056b2780d9a47eaf9bda6b2.
Retry period starts at 1 second and backs off to no more than
60 seconds.
=> feature: serial port retry logic

lib/tokensecurity.js, package.json, packages/server-admin-ui/package.json, packages/server-admin-ui/src/actions.js, test/security.js
=> fix: path to logout is not spec complient

providers/autodetect.js
- fix double output when noThrottle: true
- handle backpressure properly
=> fix: some autodetect fixes

raspberry_pi_installation.md
Thanks for all the work with the applications !
Just a thought.... maybe the row in admin UI "Server => Plugin Config" should be changed to "Server => App Config"? The term App is used everywhere for the plugins, appstore, available apps and so on.
=> Update of raspberry_pi_installation.md

lib/interfaces/tcp.js
The spec says 8375 (S K in decimal ascii).
=> chore: make delta tcp stream port compliant

packages/streams/.npmrc, packages/streams/folderstream.js, packages/streams/package.json
=> chore: add accidentally missing streams files

lib/requestResponse.js
=> fix: fail graciously when polling a nonexistent request result

package.json, test/servertestutilities.js
- fix: run test on a low speed system (Rpi) by add timeout in mocha command
- fix: bad path for test/httpprovider
=> fix: run test on a low speed system

lib/index.js, lib/serverroutes.js, packages/server-admin-ui/src/views/ServerConfig/Settings.js
=> feature: add configuration of the timeout period for lost AIS targets

lib/discovery.js, lib/interfaces/providers.js, lib/tokensecurity.js, package.json, packages/server-admin-ui/package.json, packages/server-admin-ui/src/components/Sidebar/Sidebar.js, packages/server-admin-ui/src/index.js, packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js, packages/server-admin-ui/src/views/ServerConfig/ProvidersConfiguration.js, packages/streams/simple.js
We can now discover:
* GoFree(Navico) MFDs (NMEA 0183)
* Yacht Devices YDGW-02 configured with RAW UDP port 2002 (NMEA 2000)
* Digital Yacht's WLN10 (NMEA 0183)
=> feature: add ability to discover some network connections

package.json
=> chore(package): update husky to version 2.3.0

lib/index.js
Guard against a plugin failing in plugin.statusMessage().
=> feature: safe plugin status polling

lib/index.js, packages/server-admin-ui/src/components/Sidebar/Sidebar.js, packages/server-admin-ui/src/containers/Full/Full.js, packages/server-admin-ui/src/views/Dashboard/Dashboard.js, packages/server-admin-ui/src/views/ServerConfig/ProvidersConfiguration.js, packages/server-admin-ui/src/views/ServerConfig/Settings.js
- some leftover Provider => Connection terminology changes in the UI
- make connection configuration forms linkable
- make connections and plugins clickable in the Dashboard: take the user to the appropriate config subscreen
=> Admin improvements

lib/config/config.js
This PR contains multiple commits that deal with running SignalK in Docker and kubernetes
=> Add --securityenabled option

Dockerfile, kubernetes.md, kubernetes/signalk-deployment.yaml
These commits improve the Docker image and add a kubernetes deployment. Note that this PR relies on https://github.com/SignalK/signalk-server-node/pull/822 to be merged.
=> Docker changes and kubernetes support

packages/server-admin-ui/src/components/Footer/Footer.js
=> Add name or uuid to footer

lib/deltacache.js
=> fix: detailed n2k source information not included in '/sources'

lib/mdns.js
TODO: add admin ui interface to install mdns
=> [WIP] feature: use mdsn instead of dnssd if installed

package.json
=> chore(package): update lint-staged to version 9.2.1

lib/interfaces/appstore.js
=> fix: allow server updates when installed in /usr/local

src/modules.ts
- tolerate errors better: handle the case where registry responds but responds with an error
- increase registry access timeout to 20 seconds
=> Registry fixes

package.json, settings/n2k-from-file-settings.json, src/@types/baconjs.d.ts, src/config/get.js, src/index.js, src/interfaces/plugins.ts, src/interfaces/tcp.ts, src/interfaces/ws.js, src/modules.ts, src/subscriptionmanager.ts, src/types.ts
- change default tcp delta subscription policy to `none`, see https://github.com/SignalK/specification/pull/559
- add subscription support
- sync with security policy
- If security is enabled ignore deltas coming over tcp
- If allow read only is false with security configured (no security = allowReadonly is true) disable the tcp interface
- change hello message to be the same as over ws
=> Tcp: change default policy to none, add subscription support, sync with security policy

src/serverroutes.js
=> Fix: force admin credentials minimum length

src/tokensecurity.js, test/security.js
There are certain cases where iOS won't let me set the Authorization header. Specifically when the app is not running and I try to do a background task.
=> feature: add support for X-Authorization header

src/tokensecurity.js
=> fix: do not disclose username existence

packages/server-admin-ui/src/views/ServerConfig/Logging.js
=> feature: remove chartedsails log links

packages/server-admin-ui/src/actions.js, packages/server-admin-ui/src/index.js
This makes so the server pages get updated in case something has changed during an upgrade.
=>  feature: refresh the admin ui when reconnecting

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js, packages/server-admin-ui/src/views/ServerConfig/ProvidersConfiguration.js
Currently this setting is only available directly in the config file.
=> feature: Allow editing the `toStdout` option for serial connections through the admin UI

packages/streams/n2k-signalk.js, packages/streams/package.json, src/index.js
=> fix: distinguish n2k notifications by source and fill in $source in outgoing deltas

.travis.yml
=> fix: Travis arm docker build failing on missing syscall

packages/server-admin-ui/src/components/Sidebar/Sidebar.js, packages/server-admin-ui/src/containers/Full/Full.js, packages/server-admin-ui/src/views/Playground.js, src/interfaces/inputTester.js, src/interfaces/playground.js, src/tokensecurity.js
Just getting started here, but wanted to get any input as I work on it.
The idea is to have a page in the admin ui where you can submit  0183, n2k, signalk, or canboat json data (it's auto detected).
The screen will show a table like in the Data Browser with the Signal K results. It will have an option to send the data on to the server if the user has write permission.
TODO
=> feature: provide an interface in the admin ui to manually input data

package.json, packages/server-admin-ui/package.json, packages/server-admin-ui/src/views/Playground.js, src/interfaces/playground.js
=> feature: playground enhancements

package.json
=> chore(package): update prettier to version 2.0.2

package.json
=> chore(package): update typedoc to version 0.17.3

package.json
This reverts commit 1299b0f63bc628123d1066ae1a9a59bcf5798365.
=> Revert "chore(package): update prettier to version 2.0.2"

src/config/config.js, src/serverroutes.js
Closes #996 
This can be configured by manually setting "landingPage" in settings.json
=> feature: allow configuration of the landing page

bin/signalk-server-setup, package.json, src/config/config.js, src/put.js, src/requestResponse.js, src/tokensecurity.js
Change the way to require uuid per
https://github.com/uuidjs/uuid#deep-requires-now-deprecated
=> chore: uuid@8.1.0

packages/streams/pigpio-seatalk.js
Please check the code! I'm no Python programmer. Further tests have not been done due to that there is a built in checksum which can't be inhibited in the GUI.
=> Update of the Python part

Seatalk(GPIO).md, raspberry_pi_installation.md
Instructions for the Seatalk(GPIO) connection
=> Instructions for the Seatalk(GPIO) connection

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js, packages/streams/n2k-signalk.js
This requires:
https://github.com/SignalK/n2k-signalk/pull/185
=> feature: optionally use Can NAME in source data

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js, packages/streams/tcp.js
=> feature: tcp client idle timeout

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js, packages/server-admin-ui/src/views/ServerConfig/N2KFilters.js, packages/server-admin-ui/src/views/ServerConfig/ProvidersConfiguration.js, packages/streams/n2k-signalk.js
This allows filtering out messages by Address (or Can NAME) and/or PGN
=> feature: add the ability to filter out n2k messages

packages/server-admin-ui/src/views/Dashboard/Dashboard.js, src/deltastats.js
Uptime enhancement, shows time in Days, Hours and Minutes resolution.
=> feature: uptime enhancement

packages/server-admin-ui/src/views/Dashboard/Dashboard.js, src/deltastats.js
Location changed to last on stat list.
Clean up to deltastat.js, process.uptime() was used to collect uptime.
=> feature: change uptime location on dashboard

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js, packages/streams/mdns-ws.js
- Added a button to allow to connect to a Signal K stream with a self-signed certificate
- fix issue #965
=> feature: option to connect secure Signal K stream with self-signed certificate

packages/server-admin-ui/public_src/index.html, packages/server-admin-ui/src/components/Footer/Footer.js, packages/server-admin-ui/src/index.js, src/interfaces/ws.js, src/serverroutes.js
- use vessel name in admin ui page title
- when you set vessel info propagate the new data via ws
=> feature: show vessel name in page title, propagate vessel changes

SERVERPLUGINS.md, package.json, packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js, src/interfaces/plugins.ts, src/serialports.ts, src/serverroutes.js
This includes making so `plugin.schema()` and `plugin.schemaUI()` can return a promise
=> feature: provide a way for plugins to get the list of serial ports

package.json, packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js, packages/streams/mdns-ws.js, src/discovery.js
- Automatic discovery of SignalK websocket (ws & wss)
- Alert message on older websockets with useDiscovery option
=> feature: auto discovery of SignalK websocket (ws & wss)

package.json, src/serialports.ts
TODO: make sure useful error messages are displayed when a connection or plugin is configured to use a serial port
=> [WIP] feature: make serialport an optional depedency

packages/streams/mdns-ws.js
fix: SignalK connections dashboard links
=> fix: SignalK connections dashboard links

src/index.js, src/interfaces/plugins.ts
Fix plugin links in the dashboard.
See also #1128.
=> Fix: plugin links in dashboard

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js, packages/server-admin-ui/src/views/ServerConfig/ProvidersConfiguration.js
Talking about just input is confusing, because some of the
connections may be used only as outputs.
=> fix: Input Type => Data Type

src/interfaces/plugins.ts
=> fix: do not overwrite plugin statusmessage

src/interfaces/appstore.js
=> fix: embedable web apps not showing as installed in AppStore

test/servertestutilities.js, test/subscriptions.js
Attempt to fix subscription tests by accumulating all received
messages as Promises and allowing the test code to await for
nth message (with timeout).
Simplifies the code to more procedural, await based flow.
=> fix: flaky subscription tests

packages/server-admin-ui/src/views/ServerConfig/SourcePriorities.js
=> Fix: per path sourceref lists

src/interfaces/ws.js
If you want to get meta deltas add `?sendMeta=all` to your ws url.
=> fix: don't send meta data over ws by default

src/serverroutes.js
=> fix: empty vessel base data not saved properly

src/streambundle.js
=> fix: don't send meta data over streambundle self stream

packages/server-admin-ui/src/views/Webapps/Webapps.js
This fixes the icon on the Webapps page. You'll see a couple of other lines affected where my IDE removed some spaces.
=> Issue #1195 add icon-grid to class

.github/FUNDING.yml
People asked for support possibilities on Slack, so this
is by popular demand.
=> chore: add Github funding links

packages/server-admin-ui/src/components/Sidebar/Sidebar.js, packages/server-admin-ui/src/views/Configuration/Configuration.js
=> feature: add search to the plugin configuration page

SERVERPLUGINS.md, packages/server-admin-ui/src/views/appstore/Apps/Apps.js, packages/server-admin-ui/src/views/appstore/Apps/AppsList.js, src/categories.ts, src/interfaces/appstore.js, src/interfaces/plugins.ts, src/interfaces/ws.js, src/modules.ts
=> feature: add categories to the app store

src/interfaces/ws.js
=> fix: make sure meta is sent at least once for every context

src/dummysecurity.js, src/serverroutes.js, src/tokensecurity.js
=> fix: protect against bad values for login session timeout

.github/workflows/build-docker.yml
=> feature: add Docker arm64 support

packages/server-admin-ui/package.json, packages/server-admin-ui/src/views/DataBrowser.js
=> feature: add copy buttons to databrowser

packages/server-admin-ui/src/views/ServerConfig/SourcePriorities.js
=> fix: order checking in Source Priorities editor

Dockerfile
=> feature: update docker base image to Node v16

package.json
=> chore: debug ^4.3.3

RESOURCE_PROVIDER_PLUGINS.md, packages/server-api/package.json, packages/server-api/src/index.ts, src/api/resources/index.ts, src/interfaces/plugins.ts, test/plugin-test-config/node_modules/testplugin/index.js
The beef is in 115d8f15950db68546557dc981378d5eb0a87947, making the server responsible for resourceprovider lifecycle.
=> Refactor resource provider registering

package.json, test/applicationData.js, test/deltaPriority.ts, tsconfig.json
Use ts-node to allow writing tests in TypeScript.
=> chore: add TypeScript support for Mocha tests

packages/streams/mdns-ws.js
=> fix: debug with websocket

README.md
```
git clone https://github.com/SignalK/signalk-server.git
cd signalk-server
npm install
cd packages/server-api/
npm run build
cd ../..
npm run build
```
=> chore: update building process

src/interfaces/appstore.js
=> fix: server update failing from 1.41.0 and 1.41.1

README.md, package.json
builds Signal K server and its dependencies into a single command
=> chore: build all => root & workspaces

package.json, src/api/course/index.ts, src/api/resources/index.ts, src/api/resources/validate.ts, src/subscriptionmanager.ts, src/types.ts, test/course.ts
=> More api work

src/tokensecurity.js
This was probably broken when the admin ui moved to /admin/.
Fixes #1395.
=> fix: correct login path

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js
Input Event is probably more understandable to people.
Fixes #1398.
=> feature: Sentence Event => Input Event

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js
=> doc: reword 0183 TCP server config

src/api/course/index.ts, src/api/index.ts, src/api/resources/index.ts, src/index.ts
Course api is the first one that accesse fs so that
its startup is inherently async. Make resources api
conform to the same signature.
=> wait for api startup

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js, packages/streams/tcp.js
=> feature: add idle timeout option to Yacht Devices tcp connections

packages/server-admin-ui/src/components/Footer/Footer.js, packages/server-admin-ui/src/views/ServerConfig/ServerUpdate.js
Add link in footer and a longer blurp in serverConfiguration/update
to Open Collective.
=> feature: add sponsor links

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js, packages/streams/simple.js
=> feature: add option to override timestamps

src/config/config.ts, src/config/development.js, src/config/production.js, src/serverroutes.js
=> feature: make access logging configurable

src/tokensecurity.js
=> fix: logout response as JSON

.github/workflows/build-base-image.yml, .github/workflows/build-docker.yml, .github/workflows/release.yml, docker/Dockerfile, docker/Dockerfile_base, docker/Dockerfile_rel
Base image docker creation is move to separate action and it is scheduled to run weekly, at 00:00 on Monday.
Signal K docker image creation will then use this as a base image (signalk/signalk-server-base) for dockers.
Actions updated with manually triggered option.
=> Base image creation for docker builds and actions updates

packages/server-api/.eslintrc.js, packages/server-api/package.json, packages/server-api/src/autopilotapi.ts, packages/server-api/src/deltas.ts, packages/server-api/src/index.ts, packages/server-api/src/propertyvalues.d.ts, packages/server-api/src/propertyvalues.test.d.ts, packages/server-api/src/propertyvalues.test.ts, packages/server-api/src/propertyvalues.ts, packages/server-api/src/resourcesapi.ts, packages/server-api/src/resourcetypes.ts, packages/server-api/src/types.d.ts, packages/server-api/src/types.ts
- small type fixes
- add lint & prettier, fix errors
=> chore: server-api lint & prettier, type fixes

.github/workflows/test.yml, packages/resources-provider-plugin/.eslintrc.js, packages/resources-provider-plugin/package.json, packages/resources-provider-plugin/src/@types/geolib.d.ts, packages/resources-provider-plugin/src/index.ts, packages/resources-provider-plugin/src/lib/filestorage.ts, packages/resources-provider-plugin/src/lib/utils.ts, packages/resources-provider-plugin/src/types/store.ts, packages/resources-provider-plugin/tsconfig.json, packages/server-api/src/index.ts
- add eslint to resource-provider-plugin
- improve types
- add resources-provider-plugin to CI test run
=> chore: resources-provider-plugin eslint & improvements

packages/resources-provider-plugin/src/lib/filestorage.ts
Updated resource-provider plugin to read folder contents using `withFileTypes` to identify and only process files.
=> [Fix:] Resource-Provider: process only the files in resource folders.

packages/resources-provider-plugin/README.md
Updated README to reflect that the plugin is now part of the server installation.
=> chore: Update Resources-provider documentation

packages/server-api/src/index.ts
Fix typings in server-api getXX methods.
=> fix: serverapi getXX return values

packages/resources-provider-plugin/README.md, packages/resources-provider-plugin/src/index.ts, packages/resources-provider-plugin/src/lib/filestorage.ts, src/interfaces/plugins.ts
Update `resources-povider` to use the updated ServerAPI definition.
=> fix: Resources-provider use updated ServerAPI definition.

docker/v2_demo/Dockerfile, src/api/course/index.ts, src/serverstate/store.ts, test/ts-servertestutilities.ts
Define the folder name in serverstate/store.ts and make it camelCase.
=> fix: Align the format of the folder name where server state is stored.

.github/workflows/build-base-image.yml, .github/workflows/build-docker.yml, .github/workflows/release.yml, docker/Dockerfile, docker/Dockerfile_rel, docker/README.md, docker/docker-compose.yml, packages/server-admin-ui/src/views/ServerConfig/ServerUpdate.js
Docker releasing change from Docker Hub to GitHub Container registry.
=> chore: release to ghcr.io registry

packages/streams/canboatjs.js, packages/streams/n2kAnalyzer.js, packages/streams/simple.js
We need to be able to configure the outEvents
=> feature: support multiple nmea2000 devices

Seatalk(GPIO).md
Change in the input to the optocoupler. Now using ST1 Data and supply, + 12V, instead of ST1 data and ground. New pictures + some cosmetic updates.
=> New pictures due to opto input change

src/serverroutes.ts
Busboy API changed in 1.0.0 https://github.com/mscdex/busboy/issues/266 and 7265ecb updated busboy and broke uploading to restore settings.
=> fix: restore not working

bin/log2sk
Add propertyValues in the fake app object.
Fixes #1585.
=> fix: bin/log2sk not working

packages/server-admin-ui/src/views/Dashboard/Dashboard.js
Fix for #1618
Plugin links in Connection Activity area are corrected to point Plugin Config page
=> fix: server admin ui connection activity links 

packages/server-admin-ui/src/views/security/AccessRequests.js
=> Fix: change approval button for access request to positive (green)

SERVERPLUGINS.md, packages/server-admin-ui/src/views/Dashboard/Dashboard.js
Update to Connection activity view of Signal K server admin UI.
Ingress and Egress icons:
- light blue until traffic is detected
- pulsed dark powder blue (`#039`) when traffic is detected
- solid dark powder blue after data connection opened but no traffic is detected
Values shown only when traffic detected:
- deltas/s (ingress)
- msg/s (egress)
=> feature: connection activity indicator updates

docs/book.toml
Add edit link to top right to make updates and contributions easier.
=> feature: add edit link to docs

docs/src/setup/seatalk/seatalk.md
pigpio is not compatible with the RPi 5 HW
=> Info that this Seatalk setup will not run on a Raspberry Pi 5 !!

src/config/config.ts
=> fix: add guard against empty settings file

src/tokensecurity.js
Handle NEVER special case for RememberMe cookie expiration.
Fixes #1690 .
=> fix: rememberme cookie expiration

docs/src/develop/webapps.md
Add documentation & guidance to clear up confusion about how the authentication and session management work.
=> doc: add Authentication and Session Management

src/put.js, test/put.js
Seems like this belongs in the server now.
=> feature: support PUT to notification state and method

packages/server-admin-ui/src/views/appstore/Apps/Apps.js
=> fix: error in admin ui when updating server

packages/server-admin-ui/src/views/DataBrowser/DataBrowser.js
=> fix: data browser does not allow meta to be edited for paths without any meta

packages/server-admin-ui/src/views/Configuration/Configuration.js
=> fix: plugin configuration switches in the list not updating

src/deltastats.ts
Fix output statistics not being updated properly.
=> fix: issues with provider output stats

packages/streams/gpiod-seatalk.js
Fixes issue #1788 by automatically detecting the correct gpiochip device for use with gpiod.
Please await feedback from @sailoog before merging as I don't have actual Seatalk1 hardware for testing.
=> fix: Seatalk1: Auto-detect gpiochip for Raspberry Pi 5

docker/Dockerfile_base, docker/bluez/bluezuser.conf, docker/startup.sh
Add bluez, bluetooth stack, support for docker.
Enable bluez based plugin usage, e.g bt-sensors-plugin-sk
=> feature: add support for bluez for docker

bin/log2sk
Fix the conversion utility by restructuring it to match the current pipedProviders - app interface.
=> fix: bin/log2sk

packages/server-admin-ui/src/views/appstore/Apps/Apps.js, packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/ActionCellRenderer.js, packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/VersionCellRenderer.js
there's currently no easy way to see which apps are being installed and know when all are finished
=> feature: show list of apps being installed in the app store

src/config/config.ts, src/serverroutes.ts
This reverts commit 8fdca1a25a88634c9e1408aa9bd449fb8075a733.
=> Revert "fix: communication.callsignVhf not set properly in baseDeltas.json

.github/workflows/build-base-image-test.yml, docker/Dockerfile_base_test
Ubuntu 24.04 base image for test build purposes
- including Node20 and option to change Node22 when needed
Same build and test procedure as with main base image.
=> chore: ubuntu 24.04 base image for test build purposes

packages/server-admin-ui/src/views/DataBrowser/DataBrowser.js
=> fix: no meta edit panel for notifications

packages/server-api/src/deltas.ts
Added `boolean` to Value type definition in `delta.ts` in server-api.
=> Add boolean to delta Value type definition in ServerApi

docs/src/develop/plugins/server_plugin_api.md
Add entry for `resourcesApi.getResource()` method which was missing.
=> doc: Add missing getResource() method in Resources API section.

package.json, src/interfaces/appstore.js
server is already installed and used in several other places.
Closes #1926
=> chore: use semver in place of compare-versions

packages/server-admin-ui/src/views/DataBrowser/DataBrowser.js
=> fix: copy  to clipboard

.mocharc.js, package.json, packages/server-api/package.json
This makes it easier to run a single test.
```
$ mocha test/applicationData.js course.ts
```
=> chore: extract mocha config to file

.github/workflows/build-docker.yml, .github/workflows/release.yml
Fix to remove all build time temporary image files
=> fix: docker build housekeeping to remove all temporary files
