SignalK/signalk-server

providers/gpsd.js

node-gpsd version 0.2.1 supports only the 'parse' option, and neither 'emitraw' nor 'parsejson' are supported. Fix the used options in gpsd-provider accordingly.

Fix the options for node-gpsd

---

README.md
lib/index.js
package.json

Because mDNS/Bonjour support may not be present we can not keep mdns as a hard dependency. Instead document the manual installation process and make code recover from missing dependency while keeping the 'enabled by default' behaviour.
Closes #40.

Make mDNS optional

---

lib/config/development.js
lib/config/production.js
lib/interfaces/bower.js

I get feedback from people struggling to get Signal K server & user interfaces working.
Now that we are about to have Bonjour/mDNS for discovering Signal K http server the next step in the chain is getting a reasonable response from the server. Currently it serves the configuration file, which is fine for a developer, but not really useful for a beginner.
With this change the root serves a rudimentary list of installed UI components ready for use, so the user can start with a Safari, discover the server, discover the UI and end up on a screen that shows data from the server.
The list is not pretty, but better than `{ 'signalk ready': true }`.
Next step is to fetch the list of `signalk-ui` tagged bower components from Bower registry.

Change / to return list of installed Bower Signal K user interfaces

---

package.json
providers/liner.js
settings/multiple-sources.json

Implement a way to log the raw data received from input devices in a single, hourly rolling file with timestamps. This way the raw data can be played back in the order the data was received from the various input devices, in actual rate or speeded up/slowed down.

Raw logging

---

bin/actisense-serial-n2kd
bin/n2k-from-actisense
bin/n2k-from-file
bin/nmea-from-file

Reverts SignalK/signalk-server-node#48
Wasn't quite os agnostic.

Revert "make startup scripts more shell agnostic"

---

bin/actisense-serial-n2kd
bin/n2k-from-actisense
bin/n2k-from-file
bin/nmea-from-file
bin/signalk-server
package.json

Per @lsoltero in #50, switch from bash to sh for scripts and remove bashisms.
Addresses a problem with relative path for settings files which only made it possible to call these scripts from the root of the project folder, i.e. `./bin/nmea-from-file`, but not from the `bin` directory as `./nmea-from-file` (or from any other path for that matter).
Also:
* Bump version to 0.1.20
* Use SPDX compatible license ID (Apache-2.0 vs Apache 2) see https://spdx.org/licenses/

Portable Scripts in ./bin

---

lib/interfaces/rest.js

This PR fixes a small bug in the REST interface that causes 404s on every path after `/signalk/v1/api/`.

Fixed a bug in REST interface

---

lib/interfaces/bower.js
lib/interfaces/index.js

Currently, if after installing signalk-server-node - but before running
any of the `bower install` commands - you open `localhost:3000` in a
browser window, you'll see a rather uninviting error. This makes sure
that you see the rather uninviting "Signal K Server" empty page instead.
Also, a minor edit to the regex in lib/interfaces/index.js which
requires and exports files in that directory. It only checked for the
existence of .js in filenames, now it checks for files ending in .js.
This is important if you use an editor like vim which creates .swp
files.

Fix ENOENT if bower_components is missing

---

bower.json
lib/interfaces/rest.js
package.json

Adds two new config options for the settings file:
* `proxy_host`
* `proxy_port`
Use these to advertise the hostname and port of the proxy that the
Signal K server is running behind. This way, the endpoints reported at
the `/signalk` URL will be correct.

Support Installation behind a Reverse Proxy

---

lib/config/cli.js
settings/settings.json

This corrects several issues in cli.js where paths were not handled
properly.
Also, adding a symlink to volare-file-settings.json to make the default
case of running bin/signalk-server work correctly. This is not ideal,
it would be much better to have a default settings file which didn't
actually do anything.
However, with this commit it is possible to use pm2 to run the server
as a service (and without elevated permissions).
TODO: Configure server to drop permissions if started as root

Fix path handling in cli.js

---

lib/config/config.js
lib/interfaces/rest.js
lib/mdns.js

Use the same logic to determine the host and port that are used
in mDNS/dns-sd advertisement and /signalk endpoints.

Mdns proxy support

---

README.md
lib/interfaces/rest.js

Fixes the inconsistencies between documentation, URLs advertised at the top level /signalk/ and the actual endpoints.
The SSL setting should be also handled differently in the mDNS advertisements as now we simply end up always trying to use HTTP, but I still didn't do the homework of actually reading about how exactly it works, so don't see an obvious way to do it.

Fix the REST API URLs

---

CONSUMERS.md
bower.json
package.json

Use bower as a dependancy, no need for users to install it
manually. Install the 'well known' consumers in npm postinstall.

Run bower in postinstall

---

README.md
lib/config/cli.js

Add the ability to specify the path to the settings file with SIGNALK_NODE_SETTINGS environment variable.

Settings file from environment

---

providers/serialport.js

In case of a problem on opening serial port, output an error to console log rather than just restarting.

Output error on serial provider to console log

---

providers/multiplexedlog.js
providers/timestamp-throttle.js

This PR adds a `provider` that can be used to play back logs created by the  `log` "provider".

Add provider for multiplexed logs created with log 'provider'

---

raspberry_pi_installation.md

In order to allow vessel name input with spaces in rpi-setup

Changed rpi-setup to bash

---

rpi-setup.sh

In order to allow vessel name input with spaces in rpi-setup

For vessel names with space(s)

---

rpi-setup.sh

Allows user pi to edit vessel settings file

Permissions and ownership of vessel.json

---

lib/mdns.js

This updates the way vessel_uuid and vessel_mmsi are set in the mDNS TXT record fixing a bug where either both were set to the MMSI configured in the server or vessel_uuid was set to the MMSI and vessel_mmsi was set to the UUID.

Update mDNS TXT Record Population Logic

---

raspberry_pi_installation.md

A common use case with Signal K Node Server running on a Raspberry Pi, will be someone getting everything installed, using it for the season and then coming back to it the following season and wanting to get the new and latest versions of everything.
Based on my own experiences, I added an updating guide.

Add Update Procedure to Signal K Node Server Raspberry Pi Installation Guide

---

bin/signalk-server
lib/index.js
package.json

The server now refuses to start if permissions of ssl-key.pem or ssl-cert.pem include anything but owner's read permission (400).
Fixes #143.

Refuse to start with more than 400 ssl file permissions

---

README.md
lib/interfaces/tcp.js

This PR adds TCPSTREAMPORT environment variable for overriding the default port for Signal K delta over TCP service and documents all the enviroment variables that the server honors.

Add environment override for streaming service and document environment variables

---

lib/index.js

For some reason it was ~117 hours, with pruneContexts expecting seconds and getting
7 * 60 * 1000, which clearly is a mistake.

Fix: set context (vessel) prune interval to 1 hour

---

README.md
lib/interfaces/plugins.js

This PR adds DISABLEPLUGINS environment variable, which overrides all plugins' `enabled` field to false when retrieving their configuration. Options are persisted as requested via http, but the plugins are never enabled.

Add DISABLEPLUGINS environment variable

---

lib/interfaces/nmea-tcp.js

Signalk-to-nmea0183 plugin output was not being sent over tcp, because nmea-tcp was only listening to nmea0183 events, not nmea0183out events produced by the plugin.

Fix nmea0183 conversion output over tcp

---

providers/multiplexedlog.js
providers/timestamp-throttle.js

Playback was utterly broken, in no less than three independent ways:
1. timestamp extraction was not calling the correct parameterised function so timestamp throttling was not working
2. done() was not being called, causing the pipeline to halt (masked by 1.)
3. multiplexedlog was not working as the end of a provider pipeline, because it did not emit 'data', just piped data to the next pipeline element, which is nonexistent if it is the end element

Fix multiplexed log file playback

---

lib/index.js

People frequently get a cryptic error message when starting with ancient Node. Instead show nice error message and bail out.

feature: add check for minimum Node version

---

lib/pipedproviders.js
package.json

Fixes #171. Multiplexedlog is getting stuck after 16 pushed json deltas, because
the internal buffer fills up. I have no idea why this happens with just this
provider and not others.
The deltas are actually handled with .on('data',...), so we can safely pipe
the ouput to devnull. However this is confusing - it would be better to
create a Writable  end element to the pipe and handle deltas finally
there. This way we could remove the explicit  calls
in Multiplexedlog.

fix: always consume pipeElement output with .pipe(devnull)

---

providers/multiplexedlog.js
providers/nmea0183-signalk.js

Previously 0183 playback was output with current time timestamps in
deltas. This commit adds the timestamps to the deltas that 0183 parser
emits. This assumes that 0183 parsing is synchronous so that
the timestamp stored when calling parser.write will be the correct one
when 0183 parser emits deltas.

feature: support timestamped 0183 playback with Multiplexedlog

---

lib/interfaces/rest.js

With different proxying and hostname setups you need to either
separately configure what the server should use as host and port.
Or you can use the exact same host & port used in the request that
we are responding to. The same host is used for tcp as well.
Fixes #112.

fix: use host & port from request in /signalk

---

lib/index.js

Previously a delta with context 'vessels.self' created a vessel with id
self, which confusingly had nothing to do with response to http requests
with /vessels/self path, which fetch data from under the vessel
identified with the self id from the configuration.
This fixes the situation so that deltas with 'vessels.self' context are
routed to under the vessel with the self id.

fix: handle vessels.self context properly

---

lib/index.js
lib/interfaces/rest.js
lib/interfaces/tcp.js
lib/mdns.js

Fix the default port for deltas over tcp to be 3858. Replace the hard coded
value in /signalk response with the one actually used and omit the tcp
service if it is not active. Fix mdns to use the actual port in use
in the service instead of the http/ws port.
Fixes #191

fix: tcp port in /signalk and mdns

---

lib/streambundle.js
lib/subscriptionmanager.js
test/subscriptions.js

Timestamp was not being added to deltas that were generated from
normalized delta data when sending out matches for subscriptions.

fix: timestamp in subscription deltas

---

settings/multiplexed.json

The multiplexed log example does not point to a log file for playback

Point to log file (multiplexed)

---

lib/interfaces/plugins.js
lib/interfaces/webapps.js
lib/modules.js

Npm has organisations, whose modules are under node_modules/orgname.
This adds support for the subdirectories when fetching modules
by keyword in webapps and plugins.

feature: add support for organisation npm modules

---

lib/interfaces/plugins.js
lib/interfaces/rest.js

Add support for `signalKApiRoutes(router)` hook: a plugin can
easily register /signalk/vX/api/ routes without knowledge of the exact
path where SK api is mounted.

feature: add plugin signalKApiRoutes hook

---

lib/config/cli.js

This is a switch in logic. If both mmsi and uuid are present, mmsi should be selected, as this is an unique number with an international register. #209

Use mmsi of both mmsi and uuid are present

---

lib/interfaces/charts.js

Add public/mapcache to git to make sure it exists. Use path.join to
construct the paths. Add catch blocks to handle error conditions
instead of having the errors just bubble out.
Fixes #212

fix: better mapcache error handling

---

providers/nmea0183-signalk.js
providers/serialport.js
settings/volare-serial-settings.json

This adds the ability to specify that nmea0183-signalk provider emits sentences as one
or more events. Furthermore it allows serial provider to listen for multiple events for
data to be written to serial out.

feature: allow multiple events in 0183 out and serial in

---

lib/subscriptionmanager.js

Fix for issue: https://github.com/SignalK/signalk-server-node/issues/220
Fixes subscription protocol when subscribing to AIS targets with fixed period:
```
{
context: 'vessels.*',
subscribe: [
{path: '*', period: 10000}
]
}
```
Previous implementation lost vessel data while sampling the incoming events. This fix will buffer all incoming `filteredBus` events and ensure that one value for each vessel+source+path will be emitted after the given `period`.
Remaining issues:
- Several `delta` events will be emitted simultaneously on every `period`, each containing only one `updates` value.  Optimal solution would emit only one `delta` event containing everything, but this would require some changes to the internal subscription architecture.
- `minPeriod` is left untouched and will still lose …

Fixed period AIS subscription loses updates

---

providers/serialport.js

Serialport, which is probably almost exclusively used for NMEA0183 output, should output the proper NMEA0183 line separator `\r\n`.

fix: output \r\n lineseparator in serialport

---

lib/interfaces/charts.js

Fixes #239 by treating only files that actually are in mbtiles format as chart providers.

Fix mbtiles: ignore non mbtiles files and fix mbtiles path

---

lib/index.js

If delta is missing both source and $source, use providerId as $source.

fix: use providerId as $source

---

lib/modules.js

npm search defaults to only 20 results

fix: app store can display more than 20 plugins or webapps

---

lib/interfaces/charts.js

Handle erroneous or invalid mbtilesdata files properly. This replaces #251 and fixes #252, see also #253.

Mbtiles error handling

---

lib/interfaces/rest.js

The TCP endpoint indicated on the API root (i.e. `http://localhost:3000/signalk`) was listed without the colon (i.e. `tcp://localhostXXXX` instead of `tcp://localhost:XXXX`).

add colon (:) to tcp endpoint

---

package.json
providers/log.js

Winston is needlessly complex and has a bit of overhead (for example
it clones each log message) for the rather simple task of writing
line by line timestamped logs. This replaces Winston with more
simple file writing using rotating-file-stream module.

refactor: rewrite logging provider without Winston

---

bin/nmea-from-file-filtered
package-lock.json
providers/keys-filter.js
settings/volare-file-settings-filtered.json

I needed a way to filter out specific keys that I know are wrong (heading feature on a GPS that's not working properly). This PR implements a tiny provider that gives users that option. 
**Files added:**
- `settings/volare-file-settings-filtered.json`
- `providers/keys-filter.js`
- `bin/nmea-from-file-filtered`
**Few thoughts to contemplate:**
- Should the filter remain an array of keys or be extended to support filtering specific sources? In my use case that's not a requirement, but could be useful if there are multiple talkers on a single network that all emit the same data points. It complicates things somewhat as it couples the configuration to the format of `source` in the delta (which may be different if the source is a N2K or a NMEA0183 talker) 
- Should filters *always* be exact …

Producer that allows users to filter out certain keys in a pipedProviders chain

---

lib/interfaces/nmea-tcp.js

\r\n is the correct NMEA0183 line separator. 
Detected on iSailot on Android.

Line end fix for Isailor on Android

---

lib/index.js

This pull request replaces an earlier one (#275) made which did not properly exclude several files.
From VS2017, I first needed to 'stage' the file that needed to be included

Ignore ssl file permissions if on win32

---

SERVERPLUGINS.md
lib/interfaces/webapps.js

Allow a plugin to be a webapp as well without publishing the whole
plugin module directory as static resources. Instead mount /public/
directory, if one exists.

feature: allow plugin+webapp combinations

---

lib/streambundle.js

Add a way to subscribe by path to updates that contain not only
the value available from getSelfStream() but also timestamp and
source information available from getBus().

feature: add StreamBundle.getSelfBus()

---

lib/interfaces/rest.js
test/metadata.js

With this PR the server can return schema-based metadata for all valid paths ending in `..../meta` and `.../meta/units`, which allows clients to retrieve metadata, including units, description and enum values for all paths, not just paths that the server happens to have data for.
http://localhost:3000/signalk/v1/api/vessels/foo/navigation/headingTrue/meta
```
{
units: "rad",
description: "The current true heading of the vessel"
}
```
http://localhost:3000/signalk/v1/api/vessels/foo/navigation/headingTrue/meta/units
```
"rad"
```

feature: make meta and units retrieval work on full paths

---

lib/interfaces/charts.js

If you construct mbtiles from a file system images pyramid
it may be missing name, so check instead something meaningful like
bounds to check if the file is actually a valid mbtiles file.
Fixes #300.

More robust mbtiles validation.

---

providers/nmea0183-signalk.js

When used with udp input the provider input is a Buffer,
whose conversion had an extra parameter causing nmea0183
parsing to fail and crash the server.

fix: nmea0183 buffer conversion

---

README.md
lib/index.js

Add support for configuring a tls certificate chain.
Update README https section to reflect the current state
of affairs.

feature: add tls certificate chain support

---

lib/streambundle.js
test/subscriptions.js

Subscription handling is broken: inputs like `{ path: '', value: { name: 'SomeBoat' }}` produce delta that has `{"path":"name","value":"SomeBoat"}`.
SubscriptionManager handles deltas' values independently: the
values are pushed to Bacon buses, bus per path, by StreamBundle.
When the bus's subscriptions fire SM reconstructs outgoing delta
from the incoming pathvalues. Previously StreamBundle normalized
pathvalues of naked properties, where path is empty, to synthesized
pathvalues with 'normal' paths and matching values. The generated
outgoing delta was then not naked, as it was generated from the
synthesized pathvalues.
This commit changes the handling so that the original, incoming
normalised pathvalue is pushed to buses for paths generated from
the object value's structure. Since we are …

fix: fix naked property subscription handling

---

lib/interfaces/rest.js
lib/interfaces/ws.js
lib/mdns.js
lib/ports.js

Note that you must edit /etc/systemd/system/signalk.service and add following under `[Service]`
Environment=EXTERNALPORT=80
(replace 80 with the port you are using)

fix: mdns registration failes when running via systemd

---

lib/security.js

Check that others have no access to certificate files and we have
at least read access. This allows us, for example in form
of a plugin, to write/update certificate files.
If the server generates self signed certificate files save them with 600 permissions.

fix: less strict certificate file permission check

---

lib/ports.js
lib/serverroutes.js

Extract functions for http and ssl ports and use
them instead of copied code.

fix: use correct port values in api, refactor port handling

---

lib/interfaces/charts.js

Rework chart loading logic to be more straightforward
and remove the braindead eager load that must have
never worked, just caused an extra error message that
confuses people."

fix: remove unwarranted charts error message

---

lib/interfaces/plugins.js
lib/modules.js

If a plugin is installed under the config/settings directory and also installed under the servers node_modules directory, plugin gets started twice and listed in the config UI twice.
This changes makes so that only the plugin in the config directory is used in this case.

fix: make plugins installed in config directory are preferred

---

lib/interfaces/rest.js
lib/interfaces/ws.js
lib/subscriptionmanager.js
package-lock.json
package.json
test/subscriptions.js

This feature allows ws subscriptions to be based on the relative position of the vessel. This allows the client to to only get information about other vessels that are within a specific distance. For example:
```
{
context: {
radius: 10,
position: {
longitude: -76.4639314,
latitude: 39.0700403
}
},
subscribe: [
{
path: 'navigation.*'
}
]
}
```

feature: support relativePosition.radius in subscriptions and REST requests

---

providers/autodetect.js

Multiplexed log format was not branching into `handleMixed` if  `noThrottle` option was set to `true`

Fix multiplexed log input with 'noThrottle' option

---

SECURITY.md
lib/deltacache.js
lib/dummysecurity.js
lib/index.js
lib/interfaces/appstore.js
lib/interfaces/rest.js
lib/interfaces/ws.js
lib/security.js
lib/serverroutes.js
lib/streambundle.js
lib/subscriptionmanager.js
lib/tokensecurity.js
package-lock.json
package.json
test/acls.js
test/security.js

- Fine grained access control lists (see SECURITY.md)
- Moved the simple token security code into the server
- We now send all of the latest deltas out to ws connections when the connection is made
TODO:

feature: implement access control lists

---

providers/simple.js

Without this, an error is thrown

Fix Tcp provider configuration from the UI

---

lib/tokensecurity.js
package.json

Use js-only bcryptjs instead of bcrypt with native
bindings.

chore: replace bcrypt with bcryptjs

---

lib/pipedproviders.js
providers/nmea0183-signalk.js
providers/simple.js

Simple provider created from the admin ui was not
passing nmea0183 events at all, because the logic was in
pipedprovider pipeline construction. Providers can send
events directly because they have access to the app
and app.signalk, so use that to send nmea0183 events
from the provider and remove the related logic
from pipedprovider pipeline construction.

fix: reorganise nmea0183 passing

---

admin-ui/src/views/Security.js
admin-ui/src/views/ServerConfig/ProvidersConfiguration.js

Security and ProviderConfiguration panels were erroring on Firefox because of undefined, unneede variables. 
Fixes also a React complaint about readonly JSON field, removes an unused function and removes console.logging the password when you set it.
Fixes #486

Fix Admin UI errors in Firefox

---

providers/simple.js

When the canbus interface is specified in the admin ui, it is ignored and the default is used.
Fixes #489

fix: canboatjs interface option not getting passed to provider

---

lib/interfaces/plugins.js
lib/modules.js

Makes so we prioritize loading plugins under @signalk and that we don't load multiple versions of the same plugin from different locations.

feature: allow plugins to be seamlessly moved under @signalk

---

admin-ui/src/actions.js
admin-ui/src/index.js

In looking into #449 I noticed some repeating code that could be slimed down with a generator function. The new `buildFetchAction()` builds actions that perform a basic `authFetch` to the backend. Having a generator function like this helps reduce inconsistencies and bloat. I noticed in the redux reducer sometimes the action payload is on a prop specific to the action like `plugins` or `webapps`. Other times it is more general like `data`. The builder function makes the payload prop name `data` every time. It might be worth switching to `payload` to be more inline with standards like [Flux Standard Action](https://github.com/redux-utilities/flux-standard-action)?
If cleanup like this is welcome I'm happy to continue making small, hopefully helpful cleanup changes.

Add buildFetchAction() to slim admin-ui actions code.

---

docs/CONTRIBUTING.md

Add instructions relating to PR flow and commit
messages. These have been unformalised so far. It
is a bit nasty to ask for changes in PRs when these
have been nowhere to find. Partially copied from
Angular DEVELOPERS.md.

chore: add CONTRIBUTING.md

---

lib/modules.js

If there is an issue with loading a package.json a debug log should be sufficient. I think console.log is overkill in this case.

chore: use s/console.log/debug in lib/modules

---

lib/deltacache.js

This was causing big performance issues because the full tree was being built when a request for /resources/charts is made.

fix: deltacache is building the full tree when a path that does not exist is requested

---

lib/deltacache.js

For example, the aishub sends a lot of deltas very quickly. These are getting missed because of the debounceImmediate

fix: delta cache missing very fast delta input

---

README.md
lib/interfaces/plugins.js

Add OVERRIDEENABLEPLUGINS environment option and tweak loading
of plugin settings so that we can override even if there
are no settings available.
This way we can enable some plugins by default for example in Heroku or in a preinstalled setup.

feature: add OVERRIDEENABLEPLUGINS, tweak plugin settings reading

---

lib/interfaces/appstore.js

Plugins that are also webapps were shown two times in
the appstore list. This commit change the behavior so
that they are listed only once.

fix: show dual plugin/webapps as one line in the App store listings

---

packages/server-admin-ui/src/views/Webapps/Webapp.js
packages/server-admin-ui/src/views/Webapps/Webapps.js

Make webapps list in the admin ui responsive & multicolumn. Change
the texts so that the short name is the title and description more
muted. Remove version - it is available in the App store.
Previously:
Now:

feature: make webapps list multiple columns, change text order

---

lib/interfaces/rest.js
lib/interfaces/ws.js
lib/put.js
lib/tokensecurity.js

Specifically done to enable security for node

feature: allow third party apps to integrate with security

---

SERVERPLUGINS.md
lib/deltachain.js
lib/index.js
lib/interfaces/plugins.js
test/plugin-test-config/node_modules/testplugin/index.js
test/plugin-test-config/plugin-config-data/testplugin.json
test/plugins.js

Add addDeltaInputHandler so that plugins can intercept
incoming delta messages and alter them before the server
handles them.

[WIP] feature: add registerDeltaInputHandler plugin hook

---

lib/interfaces/plugins.js

If a plugin is a web app that needs access to the configuration
data it should be able to retrieve just its own config,
not the configs for all the plugins, which was previously
the case.

feature: add per plugin config get route

---

lib/deltacache.js
test/deltacache.js

If the request is under /sources we need to build the full
based on all deltas so that the full /sources structure gets
built.
Fixes #584.

fix: /sources in deltaCache full build

---

SERVERPLUGINS.md
lib/deltastats.js
lib/index.js
lib/interfaces/plugins.js
lib/interfaces/ws.js
lib/pipedproviders.js
packages/server-admin-ui/src/index.js
packages/server-admin-ui/src/views/Dashboard/Dashboard.js
providers/execute.js
providers/mdns-ws.js
providers/serialport.js
providers/simple.js
providers/tcp.js

feature: show the status of providers and plugins on the dashboard

---

lib/deltacache.js
lib/index.js
lib/interfaces/plugins.js
lib/interfaces/rest.js
lib/interfaces/ws.js
test/history.js
test/security.js
test/servertestutilities.js
test/subscriptions.js

This adds new parameters to the ws subscribe request **startTime** and **playbackRate**. This will start the stream at the given startTime and play it back at the given rate (2 for example)
`wss://localhost:3443/signalk/v1/stream?subscribe=self&startTime=2018-08-24T15:19:09Z&playbackRate=5`
Also adds a time parameter to REST requests. This will return the vessel state at the given time.
https://localhost:3443/signalk/v1/api/vessels/self?time=2018-08-24T15:19:09Z

feature: provide an API to playback and retrieve historical data

---

raspberry_pi_installation.md

We should stick to minimum needed by Signal K Server,
people can find better and better maintained tutorials and
instructions elsewhere.

doc: remove Samba instructions

---

package.json
providers/nmea0183-signalk.js

This PR updates `signalk-server` to work with the new API of `nmea0183-signalk` introduced in https://github.com/SignalK/signalk-parser-nmea0183/pull/130
Testing I have done:
- Start `bin/nmea-from-file` and verify that data is still flowing
- Add a manual TCP NMEA provider
- Verified that data is received and parsed
- Verified that a logfile is generated when `logging: true` and that it contains NMEA data
This probably deserves more testing. Suggestions welcomed!
> **Note:**
>  this PR is marked WIP because we still need to release a new version of nmea0183-signalk and update `package.json` to point to it.

chore: update to latest version of nmea0183-signalk

---

lib/interfaces/nmea-tcp.js
packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js
providers/nmea0183-signalk.js
providers/simple.js
providers/tcpserver.js

This adds the ability to use the server's NMEA 0183
TCP server for bidirectional communications. The server listens
for 'nmea0183' events, so we will need to be able to
suppress echoing the incoming data back to the client.
Thus we need an option to suppress sending sentences
as 'nmea0183' events.
This also adds also the ability to specify one
sentenceEvent name for emitting sentences from the
0183 parser.

feature: 0183 TCP server duplex, sentenceEvent

---

SERVERPLUGINS.md
lib/deltacache.js
lib/dummysecurity.js
lib/index.js
lib/interfaces/plugins.js
lib/interfaces/rest.js
lib/interfaces/ws.js
lib/put.js
lib/requestResponse.js
lib/security.js
lib/serverroutes.js
lib/tokensecurity.js
packages/server-admin-ui/src/actions.js
packages/server-admin-ui/src/components/Sidebar/Sidebar.js
packages/server-admin-ui/src/containers/Full/Full.js
packages/server-admin-ui/src/index.js
packages/server-admin-ui/src/views/security/AccessRequests.js
packages/server-admin-ui/src/views/security/Devices.js
packages/server-admin-ui/src/views/security/EnableSecurity.js
packages/server-admin-ui/src/views/security/Login.js
packages/server-admin-ui/src/views/security/Register.js
packages/server-admin-ui/src/views/security/Settings.js
packages/server-admin-ui/src/views/security/Users.js
test/put.js
test/security.js

TODO: 
This PR provides a way for devices to request an access token from the server.  
It also has changes to conform to the new request/response and security specifications.
The device will send a REST request to the server:
`curl -k --header "Content-Type: application/json"  --request POST --data '{"clientId":"1234-45653-343453","description": "My Awesome Sensor"}'  https://localhost:3443/access/requests`
The server will return a json response with a request identifier:
`{"requestId":"60240a45-bbcb-46f0-8df6-c7a3e048bec0"}`
A Signal K notification is sent out when this happens and In the admin ui, there is a list of devices that are requesting access:
In the mean time, a device should poll the server using the requestId in the response above to see if it has been granted access and get …

feature: implement device access and new security spec

---

lib/deltacache.js

GET /signalk/v1/api/vessels/self/electrical/batteries/1/voltage
Works and has a value in it, but
/signalk/v1/api/vessels/self/electrical/batteries/1/voltage/value
returns a 404

fix: REST api to GET a value not working

---

lib/interfaces/nmea-tcp.js
lib/interfaces/tcp.js

People seem to be frequently starting the server manually
with the systemd managed one already started and the startup
fails with enigmatic EADDRINUSE 10110 stuff. This changes the
server so that it just logs error about the overlapping
NMEA0183 and Signal K server tcp ports and proceeds to
start the server.

feature: start with tcp ports in use

---

lib/pipedproviders.js

We should start with invalid provider configuration so that
the user has access to the admin UI to fix the mistake. With 
this change the valid providers will start and log the invalid
one.

feature: start with invalid provider config

---

lib/logging.js

Fix things so that log path handling works on Windows as well.

fix: make data log path handling cross platform

---

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js

This adds the text 'Select data type' to FileStream provider
configuration in the hope that the user would pick one,
instead of submitting a provider without any data type.

feature: add prompt for FileStream provider data type

---

lib/streambundle.js

Add the ability for plugins to get sourceId specific datastreams.
Current API allows only per path self streams.

feature: getSelfStream/Bus per sourceId

---

lib/serverroutes.js
packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js
packages/server-admin-ui/src/views/ServerConfig/ProvidersConfiguration.js

Change the admin UI so that the user selects the
serialport device from a popup list instead of
entering it by hand. This also creates a REST
endpoint for retrieving the list of available serial
ports.
Fixes #449

feature: use list of available serial ports

---

package.json
providers/serialport.js

Add the ability to run a command synchronously before opening
serial ports. This allows 'registering' serial ports that
the server uses in a managed environment.

feature: command to run before opening serial ports

---

lib/streambundle.js

Plugins like aisreporter use pattern
[path1, path2].map(getSelfStream)
where the array index becomes the second parameter, so
simply adding another optional parameter will
not work.

Revert streambundle changes in #682 and #648

---

.npmignore
lib/modules.js
lib/modules.test.js
package.json

Revert plugin/webapp load ordering to how it has been:
prefer modules in config directory and ignore duplicates
if they exist in server's node_modules.
Add test for the preference order.
Bring lib/modules.test.js to the fold: include it in `npm test`, that Travis uses, and npmignore all lib/**/\*.test.js\* files.

fix: plugin/webapp load logic

---

lib/config/config.js
lib/config/config.test.js
package.json

This is extracted from my failed pr #595. I am going to make smaller PRs for easier discussion.
The purpose is to make the logic that decides `app.config.configPath` easier to reason about and in its own testable function. It also helps isolate the side effect functionality of `setConfigDirectory()`.
New function `getConfigDirectory()` creates an array of possible paths in order of priority. We use [_.find](https://lodash.com/docs/4.17.11#find) to find the first truthy path value. I decided to put everything in an array so that it's easy to do a `console.log` or `debug` all available options. It's also easier to understand the priority.
A `npm run lib-test` is added to demonstrate its functionality.
I also make a couple style changes like switching `let` to `const`.
[edit]: …

refactor: Establish config dir with getConfigDirectory. Logic tested

---

lib/config/config.js
lib/config/config.test.js

Go back to how things have been working: if settings are specified with -s command line option (like bin/n2k-from-file and bin/nmea-from-file) configPath defaults to appPath, which is set to the app directory.

fix: -s settings configpath

---

lib/logging.js
package.json

Not being able to open/rotate/write in the data logging
file would crash the server. This adds error handling and
logging errors to stderr.

fix: keep working with data logging errors

---

lib/interfaces/plugins.js

The response was missing 'enabled' property if the plugin
was enabled by signalk-plugin-enabled-by-default in package.json.
Add enabledByDefault to the response
Rename the different options variables to avoid confusion.

fix: /plugins/<id> enabled with signalk-plugin-enabled-by-default

---

lib/serverroutes.js
package.json
packages/server-admin-ui/src/index.js
packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js

Canboat needs to be separately installed, so detect if it
is available and disable/enable it in the admin ui provider
configuration accordingly.
Start using /skServer serverroutes prefix.

feature: detect canboat availability

---

lib/interfaces/rest.js
lib/interfaces/ws.js
test/history.js

The [snapshot](https://signalk.org/specification/1.3.0/doc/rest_api.html#history-snapshot-retrieval) and [playback](https://signalk.org/specification/1.3.0/doc/streaming_api.html#history-playback) endpoints were changed in the process of adding these features to the specification from the original implementation in the server.
This PR changes the features to be spec compliant as two separate endpoints.
The changes are pretty heavy in ws.js, which had grown pretty unwieldy. I have tried to make its structure more sensible. The basic idea is that we now create several Primus instances, which share a lot of the functionalities related to for example security, but implement their core differently.

Spec compliant history paths

---

lib/config/config.js
test-server-as-include/package.json
test-server-as-include/run.sh
test-server-as-include/works-as-include.js

Change checkPackageVersion so that the server can be run as an included module.
Add a separate test for starting the server embedded within another Node application.
Fixes #555.

feature: server as include (checkPackageVersion, test)

---

README.md
lib/interfaces/ws.js

Add check against WebSocket send buffers growing limitlessly
if a client can or will not read the data fast enough or at all.

feature: add MAXSENDBUFFERSIZE guard against slow/dysfunctional clients

---

lib/deltacache.js
test/deltacache.js

A path with the word 'path' was not handled properly, as the deltacache
leaf detection was triggered on the object at hand having a property
named 'path'.

fix: handle delta paths with the word path

---

lib/interfaces/ws.js
test/subscriptions.js

- fixes #712:  ws upstream messages like `{ "context": "*","unsubscribe": [ {"path": "*"} ]}` killing the server because of an undefined parameter
- fix subscription error handling (inconsistent subscriptions crashing the server)
- improve ws upstream error handling so that errors in handling messages do not crash the server

fix: WebSocket related errors

---

lib/modules.js

npms.io requires a separate condition in the url to
filter out deprecated modules.

fix: exclude deprecated modules

---

README.md
lib/index.js

Resolves issue #732
Bumps the file upload limit size to 10 mb

fix: PayloadTooLargeError: request entity too large

---

lib/config/config.js

If you install signalk-server as a dependency with
npm install --save signalk-server
the admin ui ends up installed rooted at the same
level as signalk-server and the server fails to start, unless
we look for the admin ui also there.
This fix is not complete, as the admin ui will not work
like this, but the server starts.

fix: find admin ui when embedded

---

providers/autodetect.js

...pipe(autodetect).pipe(smthing)
has been working, but one more level
...pipe(ad).pipe(smthing).pipe(else)
failed, because autodetect.pipe was not
returning anything.

fix: autodetect piping

---

lib/config/config.js
lib/index.js

When the included sample files are used for demoing or testing one
often needs data timestamped now instead of the original
timestamps. Furthermore plaka.log being just raw nmea0183 data
does not contain timestamps, expect for GGA's that have time but
no date.

feature: add option to override sample file timestamps

---

packages/streams/autodetect.js
packages/streams/canboatjs.js
packages/streams/package.json

Override N2K timestamp with the value from the multiplexed log.
Depends on [a change in canboat](https://github.com/canboat/canboatjs/pull/48).

feature: use timestamp from multiplexed log

---

lib/security.js
lib/serverroutes.js

Return 404 with a nice error message if security is not configured
but a client tries to request access.
Fixes #762.

fix: access request error handling with no security

---

lib/index.js

Surround deltaChain.process with try-catch to avoid errors like
http://forum.openmarine.net/showthread.php?tid=1514 crashing
the server.

feature: more robust delta handling

---

Dockerfile

Add signalk service user to dialout (serial devices), i2c and spi
groups so that the server can have access to these devices. The group
ids are from Raspbian Lite Jessie installation.

feature: add relevant RPi groups

---

package.json

2.0.26 fails with
TypeError: geolib.isPointInCircle is not a function
at checkPosition (/Users/tjk/git-workspace/signalk/server-node/lib/subscriptionmanager.js:223:19)
Version 3 is out, so if this needs further work I suggest we
consider upgrading to that. But maybe after it settles a little
while.

chore: pin geolib to 2.0.24

---

Dockerfile
README.md
package.json
raspberry_pi_installation.md

This PR upgrades to node 10. This has been tested with:
- Debian Buster on a Raspberry Pi. Since Nodejs 10 is available in Debian Buster, this removes the need for installing node from nodesource.com
- Debian Buster on x86_64
- The Dockerfile that ships with signalk-server-node
This should solve:
https://github.com/SignalK/signalk-server-node/issues/546
https://github.com/SignalK/signalk-server-node/issues/823

Upgrade to node 10

---

lib/dummysecurity.js
lib/interfaces/rest.js
lib/tokensecurity.js

Building full from the delta cache is too slow when there's a lot of data. (takes 4 seconds on my boat). When there are no ACLs, we might as well use the in memory tree.

refactor: use the in memory full tree for REST requests

---

bin/signalk-server
package.json

Prior to Node 6 or something people frequently tried to run with
extremely old versions of Node, which resulted in not very useful
error messages. Now that we are moving to 10 in #830, but everything still
works on 8, we don't want to force upgrading and create a support
storm. So let's drop the version requirement and see what the response is.

chore: remove Node version check

---

lib/mdns.js
package.json

Handle errors from dsnsd Advertisements and use a version of
dnssd that does not throw out of band errors. Once
or if https://github.com/DeMille/dnssd.js/pull/13 or something
equivalent makes it to npm we should go back to the
upstream version of dnssd.
Fixes #850

fix: improve dnssd error handling

---

packages/server-admin-ui/package.json

react-markdown is causing warnings during server installation and that causes confusion in users, all for no reason. So let's make it a dev dependency of the admin ui, like it should be.
```
npm WARN react-markdown@4.2.2 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN html-to-react@1.4.2 requires a peer of react@^16.0 but none is installed. You must install peer dependencies yourself.
```

chore: react-markdown is dev dependency

---

packages/streams/package.json

Serialport 7.1.5 is supposed to be compatible with Node 12,
so let's upgrade to that to skip the ugly compile fails that
people experience with Node 12.
We are not supporting officially Node 12 though.
https://github.com/serialport/node-serialport/issues/1742#issuecomment-487292061

chore: serialport@7.1.5 for Node 12 compatibility

---

package.json

Globs were not quoted and thus not handled correctly. See
https://medium.com/@jakubsynowiec/you-should-always-quote-your-globs-in-npm-scripts-621887a2a784
modules.test.js was ignored inadvertedly by this.

fix: tests globbing

---

package.json
src/index.js
src/mdns.js

Apparently dnssd is abandoned, so published dnssd2.

chore: use dnssd2

---

package.json

npm install -g signalk-server will install only prod deps,
so tsc won't be there, but lib is already built during publish,
so no need for it either.

fix: do not fail in postinstall if tsc is missing

---

src/index.js
src/interfaces/appstore.js
src/modules.js
src/modules.test.js

The idea:
- a user can opt-in to a beta version
- an installed beta will keep upgrading to newer, same version
betas, like  1.0.0-beta.1 => 1.0.0-beta.2
- an installed beta will upgrade to newer release versions
- once back in a release version the user needs to opt-in to beta again
Fixes #885.

feature: support prerelease versions

---

package.json
src/interfaces/appstore.js
src/interfaces/plugins.ts
src/modules.ts

Appstore uses two registries. Now one can fail
and the store will still work with data from the
working one. The server waits for 5 seconds for the
slower registry to return and if not in time uses data
from the quicker one. The latest server version is
available only from npmjs - if it is not answering
the server check fails silently with nothing in the
ui.
Resolves #892.
Converts modules.js to TypeScript and bumps node-fetch to 2.6.0.

feature: more failure tolerant appstore

---

README.md
package.json

The postinstall script is not compatible with windows,
so it causes npm install to fail needlessly. Let's just
remove it - anybody installing with git should be savvy enough
to be able to build the server.

chore: remove linux-specific postinstall

---

Dockerfile
README.md
package.json
packages/server-admin-ui/package.json
packages/server-admin-ui/src/views/ServerConfig/PluginConfigurationForm.js
packages/server-admin-ui/src/views/ServerConfig/ServerUpdate.js
src/interfaces/appstore.js

A server running inside docker is not really updateable, as one
should pull a new image, not try to run update inside the container.
Which will not work anyway, because inside the container the
installation is not from npm.
So disable update from the admin ui and show an extra message
for Docker users. This will work with only the official images
with IS_IN_DOCKER set to true, but if you build your own image
you're on your own anyway.
Fixes #901.

Feature: disable server update when in Docker

---

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js
src/serverroutes.js

Fix the dead stupid serial port selection UI:
- add _Enter manually_ selection to the popup menu
- the text field is enabled only when the user has chosen manual entry
- manual entry is implicitly chosen if the serial port listing retrieved from the server does not contain the path saved in the configuration
List serial ports using four methods:
- /dev/serial/by-id
- /dev/serial/by-path
- /dev/ttyOP_*
- using serialport module
OpenPlotter 2 has a serial port manager that allows the user to rename serial ports with symbolic names using udev rules. On Linux there are already persistent names under by-id and lastly serialport works on at least MacOS and hopefully on Windows as well.
Fixes #880 .

Feature: improve serial port handling

---

packages/server-admin-ui/src/views/ServerConfig/PluginConfigurationForm.js

React-jsonschema-form does not work when loaded lazily, not worth
debugging why right now.

fix: revert RJSF as lazy

---

src/interfaces/ws.js

With a lot of deltas the initial burst of data upon connection may
overflow the buffer limit and terminate ws connection. At
least that is the theory.

fix: increase ws MAXSENDBUFFERSIZE

---

package.json

This allows the use of the --no-optional npm install flag to get a minimal install with no default plugins

feature: make default installed plugins optional dependencies

---

src/config/config.js

If the defaults.json has syntax errors, the file is overwritten and the server starts up normally. 
This change makes so we log a good error message and fail to startup.

fix: invalid defaults.json gets ignored and overwritten

---

bin/log2sk

log2sk worked only on case-insensitive file systems, like MacOS that
defaults to case-preserving but case-insensitive.
Fixes #948.

fix: log2sk case sensitive file reference

---

package.json

demo.signalk.org is hosted in Heroku and autodeploys from latest-release
branch, so update that when creating a release. Afaik Heroku can't
autodeploy a tag, so we can't hook it up to latest tag.

feature: update latest-release branch when releasing

---

packages/streams/mdns-ws.js

fix issue #964 (Cannot subscribe to Signal K stream non SSL/TLS)

fix: useTLS vs useSSL with signalkClient

---

src/interfaces/rest.js

Allow a historyProvider plugin to register under /signalk/v1/history/*.

[WIP] feature: add support for history api plugin

---

packages/streams/mdns-ws.js

second fix for issue #964 (Cannot subscribe to Signal K stream non SSL/TLS)
use correct protocol with websocket.
Sorry, I fired too fast the first time and I didn't see the second mistake right next to it.

fix: use correct protocol with websocket

---

packages/streams/nmea0183-signalk.js

This fixes a bug where sentenceEvents were emitted only on
`app.signalk`, but the toStdout configuration only allowed us to listen
on `app`. This fixes it by emitting on both, as discussed on Slack
earlier today.

fix: Emit sentenceEvents on both `app` and `app.signalk`

---

src/security.js

On Windows the fs.stat function returns inconsistent values.
The checking of the SSL certificate file attributes has been removed on Windows only.
Fix issue #982

fix: do not check TLS certificate file permissions on win32

---

packages/server-admin-ui/src/views/ServerConfig/VesselConfiguration.js
src/serverroutes.js

Add VHF Call Sign to Vessel data as configurable parameter and make it available in /communication/callsignVhf. #1018

feature: add vhf call sign to UI and make it configurable

---

src/interfaces/ws.js

Add the option to suppress sending of latest values when
WebSocket connects. This can be done with query parameter
sendCachedValues=false. Any other value or no query parameter
with that name results in previous behavior, sending all
the relevant latest values as deltas.

feature: add sendCachedValue ws query parameter

---

packages/streams/serialport.js

After this change only the first error related to each configured
serialport is logged to stderr. If the port is connected then
the first error is logged again. Errors related to retries
are logged only on debug level, with debug key signalk:serialport.

fix: less logging from serial retries

---

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js
packages/streams/mdns-ws.js
packages/streams/package.json
packages/streams/simple.js

Update to using SignalK js client ^2.1.0 and add needed changes so that the server can connect to SK servers without subscriptions support, using query parameter `all`.
Add the option to map the remote SK server's self to local `self`, either automatically by getting the remote server's self via http api or explicitly configuring the remote self id manually.
The mapping removes the context from the incoming self deltas, allowing the server to treat them like they were coming from a local provider.

Fix ws connection query string(iKommunicate) and add self mapping to ws Signal K connections

---

packages/server-admin-ui/src/components/Sidebar/Sidebar.js
packages/server-admin-ui/src/containers/Full/Full.js
packages/server-admin-ui/src/views/ServerConfig/Settings.js
packages/server-admin-ui/src/views/ServerConfig/VesselConfiguration.js

Reduce the number of items under admin menu 'Server' by grouping
server settings, vessel configuration and data log panels
on a single page.
Rename Playground to Data Fiddler to better(?) reflect what it is:
a place where you can fiddle with (input) data.

feature: reorganise and rename admin components

---

package.json
test/deltacache.js
test/metadata.js
test/multiple-values.js
test/plugins.js
test/servertestutilities.js
test/subscriptions.js

request-promise was only used in tests and can be easily replaced
with the more familiar fetch.

chore: remove request-promise

---

src/interfaces/webapps.js

The user can replace the logo at the top left of the admin
app by placing an svg file named 'logo.svg' in the settings
directory.

feature: add custom logo

---

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js
packages/streams/replacer.js
packages/streams/simple.js

Add options to ignore null characters from the 0183 input and
configurable 0183 sentences to remove from the input stream.
Fixes #970

feature: add null removal and ignored sentences to 0183 input

---

packages/server-admin-ui/scss/_custom.scss
packages/server-admin-ui/src/views/Configuration/Configuration.js

- limit the card width as the form content is pretty columnar
- do not force inputs to be 100%
- less emphasis on field descriptions
- less vertical margins, more compact
- make array items more distinctive with a background
Previously:
Improved:

feature: improve plugin config form layout

---

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js
packages/streams/tcp.js

Add sending to defined stdout events to TCP connection.
As similar option is available in the serial connection
Fixes #1054
Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

feature: add stdout sending to TCP Client connections

---

packages/server-admin-ui/src/views/Playground.js

The output tab was still '5' for the jsonError display
even after the error had gone away and Output was showing
nothing.

fix: reset fiddler output tab after error

---

packages/streams/canboatjs.js
packages/streams/execute.js
packages/streams/gpsd.js
packages/streams/keys-filter.js
packages/streams/logging.js
packages/streams/mdns-ws.js
packages/streams/n2kAnalyzer.js
packages/streams/nmea0183-signalk.js
packages/streams/s3.js
packages/streams/serialport.js
packages/streams/tcp.js
packages/streams/udp.js
src/interfaces/nmea-tcp.js
src/interfaces/tcp.ts
src/mdns.js
src/security.js
src/tokensecurity.js

Main server code uses signalk-server prefix, streams
signalk:streams prefix as it can be used outside the server
context.
Partial fix for #1031.

chore: harmonise debug names

---

src/interfaces/appstore.js

Currently, if plugin installation fails, the plugin is removed from the Available list it the user cannot try again without restarting the server. This change puts the plugin back in the available list after an install fails.

fix: allow retry installing a plugin after it fails

---

src/tokensecurity.js

The spec says one can provide the token in
Authorization: Bearer <token> header.
https://signalk.org/specification/1.4.0/doc/security.html#websockets-clients

fix: support for token in Authorization: Bearer header

---

src/index.js

This adds the ability to debug log all server 'app'
events, useful to see events' data in the server log.
The eventDebugs debug function cache could be used to provide
a popup menu in the UI to select events that the user
wants to see in the server log.
The event debugs are named signalk-server:events:<eventname>

feature: debug all server events

---

bin/signalk-server

Now uncaught exceptions crash the server, which makes
debugging things a bit hard, as the server may be crashing
so that admin ui is not available and the server log that
way even less so.
This adds a global error handler that simply logs the error.
This should provide easier access to errors in the server
log and keep the server up, even if for example a misbehaving
plugin is not handling its own errors.
For example an interface or a plugin that does somethiing like this 
```
setTimeout(() => {
app.emit('error', new Error('crash-u'))
}, 1000)
```
will cause a crash with 
```
events.js:174
throw er; // Unhandled 'error' event
^
```

Feature: add global error handler

---

Seatalk(GPIO).md
packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js
packages/streams/execute.js
packages/streams/pigpio-seatalk.js
packages/streams/simple.js
raspberry_pi_installation.md

@MatsA @Thomas-GeDaD here's SK server code that
- adds a new connection type `Seatalk`
- forks a dummy Python process that just prints STALK sentences
So if you can provide a Python script that reads serial and produces STALK output this should work.
If you want to try this branch out you need to performa these steps:
- clone the repo and checkout this branch
- npm install
- compile the server code with `npx tsc`
- cd packages/server-admin-ui
- npm install
- npm build
- npm link
- cd ../..
- npm link @signalk/server-admin-ui
- cd packages/streams
- npm link
- cd ../..
- npm link @signalk/streams
This will link the admin ui and streams packages from the main server and compile the server and the ui so that they work together.

feature: add seatalk connection type

---

packages/streams/pigpio-seatalk.js

This change reduces CPU usage from 100% to less than 10%.
Some background: https://forum.openmarine.net/showthread.php?tid=2774&pid=15489#pid15489

reducing CPU consumption in seatalk 1

---

package.json
packages/streams/package.json

Update to latest version of serialport that support Node 14,
that people seem to bump against.
Add the real serialport dependency at root, so that it gets
installed there, and make it optional in streams, so that even
without it the other streams' install succeeds.

chore: serialport@9

---

packages/server-admin-ui/src/views/DataBrowser.js

- make DataBrowser default to self context
- change paths search to be case insensitive so you can search with for example _apparent_ and match _Apparent_

feature: DataBrowser self default and case insensitive search

---

packages/server-admin-ui/src/index.js
packages/server-admin-ui/src/views/ServerConfig/ServerLog.js
src/serverroutes.js

Add a list of checkboxes for all debug keys known in server's
Debug. Keep the text field also, so that you can enter wildcards, but
keep both checkboxes and text field working.
Reorganise the Server Log view a little: associate the Pause button
with the actual server log and gather all Debug related stuff at
the top.
Reindent all the jsx code.

feature: checkable list of debug keys in Server Log view

---

packages/streams/serialport.js

fix: connection status for serial ports ( issue #1144 )
Avoid sending an empty message that deletes the providerStatus

fix: connection status for serial ports

---

CHANGELOG.md
README.md
docs/CONTRIBUTING.md
packages/server-admin-ui/package.json
packages/server-admin-ui/src/views/ServerConfig/ServerUpdate.js
src/interfaces/appstore.js

- remove CHANGELOG:md and references to it in .md files
- replace dummy changelog with a link to Github releases in the admin ui
- improve admin ui by adding a loading text when app store is not yet available
Includes a little fix to admin ui dev mode.

Fix: clean up Server Update in Admin UI

---

src/interfaces/plugins.ts

app.setProviderStatus was accidentally renamed app.setPluginStatus
in plugin api, which exposed the real app.setProviderStatus where
the first parameter is the id, not the message.

fix: setProviderStatus for plugins

---

SERVERPLUGINS.md
src/interfaces/plugins.ts

feature: add setPluginStatus/Error and deprecate setProvider versions 
Start actively deprecating 'Provider' concept, starting with plugins, that
never were providers in the first place.
Logs usage of either of the old versions once with a url that points to the
documentation. I tried to craft the message to be neutral enough so that
we don't get support requests from end users about this.
No idea if we can ever really deprecate these without having all plugins that
have not been updated for ages also deprecated, but it's a start."

Deprecate plugin set provider xx

---

src/interfaces/rest.js

If the SSL connection is terminated on a load balancer then SK is not
aware that clients should use https. This change allows SK to look for
the x-forwarded-proto header so that it knows the connection should use
https.
For this to work the load balancer must provide the x-forwarded-proto
header.

feature: allow ssl to be terminated on a load balancer

---

packages/streams/n2kAnalyzer.js

If analyzer output parsing fails we can log the offending
input to help troubleshooting.

fix: log offending input in n2kAnalyzer

---

packages/server-admin-ui/src/views/ServerConfig/ProvidersConfiguration.js

Several people have missed the Data Type selection, because the connection
form is scrolled to the top of the window, not to the top of the visible area.
This hardcodes the header's height as scroll-margin-top so that the top of
the connection form is visible and we don't look like we have support only for
NMEA 2000.

fix: scroll properly to connection form's top so that Data Type is shown

---

src/interfaces/ws.js

The unauthenticated connection gets severed by the server after 60 seconds.

fix: unauthenticated subscriptions allowed when allow read only is off

---

packages/server-admin-ui/src/actions.js
packages/server-admin-ui/src/views/Configuration/Configuration.js
packages/server-admin-ui/src/views/Playground.js
packages/server-admin-ui/src/views/ServerConfig/BackupRestore.js
packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js
packages/server-admin-ui/src/views/ServerConfig/Logging.js
packages/server-admin-ui/src/views/ServerConfig/ProvidersConfiguration.js
packages/server-admin-ui/src/views/ServerConfig/ServerUpdate.js
packages/server-admin-ui/src/views/ServerConfig/Settings.js
packages/server-admin-ui/src/views/ServerConfig/SourcePriorities.js
packages/server-admin-ui/src/views/ServerConfig/VesselConfiguration.js
packages/server-admin-ui/src/views/ServerConfig/main.jsx
packages/server-admin-ui/src/views/appstore/Apps/AppsList.js
packages/server-admin-ui/src/views/security/AccessRequests.js
packages/server-admin-ui/src/views/security/Devices.js
packages/server-admin-ui/src/views/security/Settings.js
packages/server-admin-ui/src/views/security/Users.js
src/constants.ts
src/interfaces/appstore.js
src/interfaces/plugins.ts
src/interfaces/providers.js
src/interfaces/webapps.js
src/serverroutes.js
src/tokensecurity.js
test/plugins.js
test/providers.js
test/security.js

This PR moves all endpoints that are not part of the Signal K specification and mostly for managing the server and its function under common `/skServer` prefix.
The motivation for the change is to
- make it explicit which parts of the api are server-specific and not part of the standard
- leave root paths uncluttered
The PR leaves `/loginStatus` available both at the old and new path so that any webapps that depend on it can smoothly transition to using the new path. Or we can add it to the official `/signalk` api.

feature: move server management endpoints under /skServer

---

src/interfaces/appstore.js
src/modules.ts

Close file connections before updating the server to avoid interrupting the update process.
fix issue #1170

fix: close file connections before updating the server

---

src/interfaces/appstore.js

getLatestServerVersion was being called without the currently
installed version and that shows the latest release as the
latest, so the APP_STORE_CHANGED event did not contain the
installing: true data.

fix: beta update not showing as installing

---

packages/server-admin-ui/src/views/security/Settings.js
packages/server-admin-ui/src/views/security/Users.js

Not acting on componentDidUpdate caused these pages to show
incorrect / no data when used with a direct url, like when you
reload the page in server.
A better fix would be to have this data in Redux and not handled
independently on the page itself. Sending updates via serverevents
would allow all open admin pages to update and not require a reload.

fix: security settings with direct url

---

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js

The value is in seconds, so fix the label.

fix: tcp timeout label

---

packages/server-admin-ui/src/views/Configuration/Configuration.js
packages/server-admin-ui/src/views/ServerConfig/PluginConfigurationForm.js

Move `enable`, `enableLogging` and `enableDebug` switches outside the
rjsf generated form, with autosave. This enables plugins to provide
their own configuration forms, keeping the server-managed config
properties outside the form.
Along the way remove the Redux connect dependency on serverstatistics as
the data on the page is independent from that data.

feature: inline plugin main switches in the plugin list

---

packages/server-admin-ui/src/views/appstore/Apps/AppsList.js
packages/vesselpositions/package.json
src/interfaces/appstore.js
src/interfaces/webapps.js

Load embeddable webapps explicitly, not relying on `signalk-webapp` keyword.
Make vesselpositions just an embeddable webapp, not a plain webapp.

Embeddable webapps as webapps

---

TROUBLESHOOTING.md
src/index.js
src/logging.js

This changes the ordering in startup so that config is loaded first, then
logging that uses config to find the settings directory. So if you need
to debug log settings you need to use an env variable.

feature: move debug log settings under .signalk

---

package.json

Version 4.3.0 removed `instances` which was causing issues with the ServerLog page

fix: hard code debug module to 4.2.0

---

src/interfaces/plugins.ts

Now that plugin enable is outside the plugin configuration form and
not part of it the user may enable the plugin without touching the
configuration. Without this check the plugin gets passed undefined
as configuration, that most plugins probably won't expect and will
fail. The failures should not affect the server's base functions,
but the log messages can be cryptic.

fix: safe plugin configuration object

---

src/interfaces/appstore.js

fix: #1203  plugins with tag signalk-webapp only are not displayed in the appstore.

fix: display of webapps in appstore with tag signalk-webapp only

---

packages/streams/execute.js

nmea2000out configured as stdout event by [streams/simple](https://github.com/SignalK/signalk-server/blob/f02bbb5807e0d238b202445f1cd25ab09d4682cd/packages/streams/simple.js#L251-L256) tried to
also subscribe to nmea2000JsonOut events with conversion in place,
but because the event name was not correct this has never worked.
This commit fixes the event name, writes to child process's stdin
and adds require for the conversion function.

fix: nmea2000 output with canboat

---

.github/workflows/build-docker.yml
Dockerfile

Docker build on Travis and push to Docker Hub is a bit clunky, especially the multiarch part.
This PR adds a Github Action to build x86 and arm multiarch image and push it / them to Docker Hub. The images are additionally tagged with short commit SHA:
The tags created per branch are like so:
```
#24 pushing manifest for docker.io/signalk/signalk-server:ghcr
#24 pushing manifest for docker.io/signalk/signalk-server:ghcr 1.0s done
#24 pushing layers 1.1s done
#24 pushing manifest for docker.io/signalk/signalk-server:sha-868318a
#24 pushing manifest for docker.io/signalk/signalk-server:sha-868318a 0.8s done
```

chore: convert Docker builds to Github Actions

---

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js

The bidirectional nature of the serial ports seems to confuse people, so add a note about it in nmea0183 serial connection context.

doc: add help text about bidirectional serial connections

---

package.json
src/modules.test.js

Do not install sailgauge and simplegauges by default, as they
are getting a little dated. Furthermore one can not get rid of
any of the default webapps, as they are going to be reinstalled
with next server update.

feature: remove old webapps

---

src/interfaces/rest.js

Fixes #758.
The rest handler can shortcut known other path prefixes early
in the processing. The issue in #758 is way less pronounced
now, I think deltacache was in more use at the time of the
writing, but I think this shortcut makes still sense.

feature: shortcut resources handling in rest.js

---

SERVERPLUGINS.md

The change from `app.setProviderStatus(msg)` to `app.setPluginStatus(msg)` was not done in sample code

fix: changed to app.setPluginStatus in sample code

---

packages/server-admin-ui/src/views/Configuration/Configuration.js

This changes the plugin configuration logic so that the
enable/log/debug switches are not shown unless the plugin
has configuration data. Instead we show a Configure button
that opens the configuration form, that closes on first
submit. On first submit it also enables the plugin.
Fixes #1164 as the configuration form is closed on submit.

feature: disable plugin enable without configuration

---

Dockerfile

Non-Docker default setup set current working directory as
/Users/tjk/.signalk. This is a pretty sane default, as for example
files created from non-SK stuff like node-RED end up in
the settings folder. In practise Docker users will manage
the settings directory themselves, so this works also
in that respect.

feat: set current working directory in Docker

---

packages/server-admin-ui/src/views/Configuration/Configuration.js

It was not possible to enable plugins that have no properties. This
changes activates the Enable plugin toggle even if there is no configuration
data, if the plugin's config schema has no properties.

fix: support plugins with no properties in schema

---

src/interfaces/nmea-tcp.js

The data is a Buffer, emit as string.
Fixes #1254.

fix: tcpserver0183data toString()

---

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js

Fixes #1252 . Makes connection id alphanumeric with - and _ and disable editing the id for existing connections, as that does not work.

feature: more strict connection id naming, disable edit

---

src/tokensecurity.js

ACL filtering was modifying a shared delta's updates. In a case
where the first handled ws connection would not have access to
a path a second ws connection would get served the same delta where
the limited access path was no longer there.

fix: concurrent delta ACL filtering

---

README.md

fix on example docker cmd line for the following error using the --entrypoint as previously documented
```
[FATAL tini (7)] exec bin/signalk-server failed: No such file or directory
```

Docs: Update README.md for docker command line error

---

src/interfaces/plugins.ts

Reverts SignalK/signalk-server#1268
This change made so plugins could be enabled without configuring them
Now there's a little display issue, but this problem is much worse.

revert: "fix: existing plugins with no configuration don't show properly in the ui"

---

src/interfaces/plugins.ts

Sometimes users would see their plugin configurations looking empty, even if the configuration file is there with the content.
This fixes a race condition, where we were reading the configuration data to be sent to the plugin configuration UI while a plugin's configuration data was being written and the ui would see an empty configuration.

fix: plugin configuration being occasionally empty

---

src/config/config.js

feat: Process  --override-timestamps even if --sample-n2k-data or --sample-nmea0183-data are not specified

feat: Process  --override-timestamps unconditionally

---

src/tokensecurity.js

Security configuration validation introduced in #1267 had an
error in testing the login session timeout.
https://www.npmjs.com/package/jsonwebtoken#jwtsignpayload-secretorprivatekey-options-callback
'exp or any other claim is only set if the payload is an object literal.'

fix: security configuration validation

---

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js

Setting to True suppresses data in 10110 output so it's not duplicated when using SignalK to NMEA0183 plugin. 
This PR just exposes this setting in the server config page for all NMEA data providers.
Fixes #1319

expose Suppress0183Checkbox in all NMEA1083 connection configurations

---

src/config/config.js

It is better to maintain one single file for metadata and static values.

feat: use baseDeltas by default

---

packages/server-admin-ui/src/views/ServerConfig/Logging.js
packages/server-admin-ui/src/views/ServerConfig/Settings.js
packages/streams/README.md
packages/streams/logging.js
src/interfaces/logfiles.js
src/serverroutes.js

On a memory limited device like Raspberry PI unlimited growth of the log files is undesirable.
This changes adds two controls to the Server Settings panel:
- Switch "Keep only most recent logs" to enable/disable this feature
- Input "How many hourly files to keep" allows user to specify how many most recent hourly logs the server will keep
Since it's difficult for the mobile user to download text files one by one the button [Get all logs in one ZIP] is added.

feat: add optional setting for log files to keep and downloading all log files as a zip file

---

packages/server-admin-ui/src/views/ServerConfig/Settings.js

Allow disabling only the interfaces that a normal user
might want to disable, and not all the interfaces. The
interfaces list structure is a relic with not much
relevance. You can still disable all the interfaces
by manually editing the settings file, but this makes
it so that you can not accidentally lock yourself
out of the admin UI.
Includes minor styling changes to get the switch labels
aligned a little more nicely.

feature: clean up interfaces settings

---

bin/signalk-server-setup

Make signalk-server-setup add NODE_ENV=production environment variable.

feature: NODE_ENV=production

---

packages/server-admin-ui/src/views/ServerConfig/SourcePriorities.js

Fixes #1343.
Source selection in Source Priorities setup was
not working for paths that had more than one
period in them.

fix: source priorities with >1 periods

---

README.md
raspberry_pi_installation.md
src/modules.ts

It seems that the transitive dependency that originally caused the
need for --unsafe-perm is no longer there/no longer requires
the extra permissions. SK server's functioning never needed
the extra permmission level, so let's remove that.

feature: remove --unsafe-perm

---

src/interfaces/plugins.ts

A single plugin that uses schema's function form whose schema() call
throws an error could prevent the server's plugin configuration ui
form page from loading.
This adds a guard against errors thrown in schema() call. The error
is logged and a fake schema containing a single field with a name
indicating that the schema could not be loaded. Problem with this
fake schema is that saving it may overwrite a perfectly good
plugin configuration, but it is a cheap way to show something is wrong.

fix: guard against plugin.schema() errors

---

packages/streams/nmea0183-signalk.js

Use debug instead of console.error changed in 55fe8aa553684f83bf429da37992461793a5f5f2
otherwise people get too verbose logging under normal conditions with some
unrecognised sentences.

fix: nmea0183-signalk logging

---

raspberry_pi_installation.md

Added link to Wiki for how to upgrade to Node.js 16.

doc: update RPi instructions for Node.js 16 / 1.41

---

Dockerfile

With npm workspaces @signalk/server-admin-ui is no longer
being installed from npm, so we need to build it explicitly.
Run npm install before any of the builds so that it runs
in all workspaces, no need to run it separately.

fix: admin ui in docker

---

src/subscriptionmanager.ts

Changed in #1356. Subscribing for path: '' should not
match everything, just pathvalues with an empty path.

fix: subscribe for path '' should not match all

---

src/interfaces/ws.js
src/tokensecurity.js
test/security.js

When authorizing WebSocket connection the JWT was just
decoded, not verified.
This changes decode to verify and now JWTs with an
invalid signature are rejected and the caller sees a
401 response.

fix: ws JWT verification

---

src/tokensecurity.js

Previously bad tokens (whose verification fails for one reason or another)
were not cleared in http requests if read only access was on. After
#1401 ws requests are closed with 401 status code if the token can not
be verified. This resultedin a state where the admin UI loaded but
websocket did not connect. This is not very useful, because read only
access over ws does not work and admin ui shows an annoying "Not
connected to the server" error message.
There is no use for bad tokens from cookies, so we can outright delete
the cookie whenever token verification fails. This handles for example
token expiration, falling back to read only access if it is available.
In browser use there are always http requests prior to opening the ws,
so bad token cookies are cleared before opening ws.

feature: clear bad token cookies in http requests

---

src/interfaces/ws.js

Expired tokens should result in 401 response in the ws endpoint.
Missed in #1401.

fix: close ws with 401 if token is expired

---

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js

The default for suppressing 0183 event should be off, otherwise incoming 0183 data is not getting routed to tcp/10110 as it has been traditionally.
This was exposed to all 0183 connections in #1321 and having it on by default no longer makes sense for all new 0183 connections.

fix: do not suppress 0183 event by default

---

packages/server-admin-ui/src/containers/Full/Full.js
packages/server-admin-ui/src/views/Playground.js

Data Fiddler was crashing if the delta had any values
as null. This showed up as a blank page after entering input data that created such a delta and you would need to clear the bad data from localStorage to get Data Fiddle working again.
This PR also adds a per page error handler that should keep the rest of the UI working even if a single subpage is crashing.

fix: data fiddler null value handling & UI crash remedy

---

package.json
packages/server-api/src/resourcetypes.ts
src/@types/api-schema-builder.d.ts
src/@types/geojson-validation.d.ts
src/api/course/index.ts
src/api/course/openApi.json
src/api/resources/index.ts
src/api/resources/openApi.json
src/api/resources/resources.ts
src/api/resources/validate.ts
test/course.ts

Use the schemas in openapi definition to validate resources api payloads. The main idea is that `validate` just throws if the data is not valid and the errors are propagated to the client as payload of the 400 response,

Resources api schema validation

---

src/serverroutes.js

There are occasionally reports of admin ui index html cached and that
causing trouble, like in #1408, so let's add explicit no cache headers
to it.

feature: disable caching admin UI index.html

---

src/serverroutes.js

After a backup/restore of the server the Name, MMSI, ... parameters are not restored.
The `baseDeltas.json` file is present in the backup but it is not restored
issue: #1421

fix: baseDeltas.json is missing in restore process

---

src/interfaces/appstore.js

Fix:
issue when no Internet connection
move error messages form console.log() to debug()
Issues:
https://github.com/SignalK/signalk-server-windows/issues/15 (SK crashes when run as services without internet access)
https://github.com/SignalK/signalk-server/issues/1420 (Handle npm timeouts gracefully)

fix: appstore when no Internet connection

---

src/deltacache.ts

Sending pathvalues without either path or value in
delta would cause delta retrieval from deltacache to
fail with infinite recursion. So after such a 'poison'
value in any delta cache retrieval would start failing
until a new value would be written for that path in the
cache.

fix: add guard against bad pathvalues in deltacache

---

packages/server-admin-ui/src/views/security/Settings.js
src/index.ts

If you want to use any of the http APIs from
another origin with credentials you can not use just
a wildcard origin, CORS rules don't allow that.
This adds a setting under security that allows configuration
of one or several allowed CORS origins.
A practical use case for this is when you use the (wip)
history API from Grafana Signal K datasource. Grafana
typically runs on another port, making the requests from
Grafana UI cross domain.

feature: allow configuring CORS origins explicitly

---

src/subscriptionmanager.ts
test/subscriptions.js

Period and minPeriod do not quite make sense with
empty path subscriptions: for different values the
path is the same, so how do you send data only every
x milliseconds, as it means dropping some of the
values and not sending them at all.
This changes subscription handling so that period
and minPeriod are silently ignored for subscriptions
with an empty path.
Fixes https://github.com/SignalK/freeboard-sk/issues/108

fix: empty path subscription period handling

---

src/interfaces/providers.js
test/providers.js

Change provider api response texts to use Connection
instead of Provider, because they are shown to the end
user and admin UI uses Connection term.

fix: Connection in ui messages

---

.github/workflows/release.yml
.github/workflows/require_pr_label.yml
package.json

Use actions to create release notes off labeled PRs and release
itself, triggered by tags.

chore: automate Github Release creation

---

WEBAPPS.md
packages/server-admin-ui/src/views/Webapps/Webapp.js
packages/server-admin-ui/src/views/Webapps/Webapps.js

Add support to determine how a webapp is displayed in the WebApps list including an icon by adding the following section in package.json:
```JSON
"signalk": {
"appIcon": "./assets/icons/icon-72x72.png",
"displayName": "Freeboard-SK"
}
```
where:
- `appIcon` is the path (relative to the public directory) to an image within the package to display in the webapp list. The image should be at least 72x72 pixels in size.
- `displayName` is the name to appear in the webapp list which will override the use of the `name` attribute in the package.json.
(closes #629)

Feature: Webapp icons

---

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js

With several connections of the same time switching between them
would show values from the previously chosen one.

fix: some connection settings show wrong values

---

packages/streams/simple.js
packages/streams/udp.js

These changes allow transmitting NMEA 2000 data over YDWG RAW UDP
broadcasts. This allows for wireless N2K connectivity via a suitable
gateway device.
At the moment, the server _does not_ do address claims or other
N2K protocol red tape over the YDWG RAW UDP interface.

feat: implement YDWG RAW transmitting over UDP

---

src/serverroutes.js

Fixes #1450.
Saving the form with some unchanged values that came from
the server would reset them, because the value from the
server is already a Number and the extra .length check
would fail.
The fields affected were the object valued fields:
- aisShipType
- length
- draft

fix: setting vessel object parameters

---

packages/streams/mdns-ws.js
packages/streams/package.json

This addition makes ws client send periodic "keepalive" messages to the server. If the connection is no longer alive this will prompt the OS to eventually kill it, instead of keeping it lingering for ever.
This is still not perfect, as it is up to the OS settings to detect dead connections. We should implement keepalive / heartbeat messages from the server to make detection more deterministic, quicker and configurable.

feature: improve detection of dead SignalK to SignalK connections

---

docker/Dockerfile

GH Action builds are failing with
npm ERR! code ERR_SOCKET_TIMEOUT
let's see if this improves things.

chore: increase npm fetch timeout

---

README.md
package.json
packages/server-admin-ui/src/components/Sidebar/Sidebar.js
src/api/apps/openApi.json
src/api/apps/openApi.ts
src/api/discovery/openApi.json
src/api/discovery/openApi.ts
src/api/security/openApi.json
src/api/security/openApi.ts
src/api/swagger.ts
src/interfaces/rest.js
src/serverroutes.ts
tsconfig.json

This PR 
- adds the Swagger UI to the server, including a link to it from the Admin UI
- adds OpenAPI descriptions of the discovery api at /signalk and the security api
The goal is to introduce OpenApi to Signal K by creating descriptions of parts of the v1 API that are very OpenAPI compatible.
One idea here is to carve stuff off #1477 - stuff that can be published without getting into messy v1/v2 compatibility issues.
Based on #1490.

feature: add Swagger and first OpenApi descriptions for discover and security/authentication APIs

---

package.json
packages/server-admin-ui/src/views/security/Settings.js
public/examples/loginform.html
src/cors.ts
src/index.ts
src/security.ts
src/serverroutes.ts

CORS was previously not enabled for any of the security related routes, specifically `/signalk/v1/auth/login. This PR changes the order in server setup so that CORS middleware is activated before security routes. Fixes #1479.
Without any origins configured the server allows CORS requests from any host.
However when configured the origin list was not working correctly:
- the first configured origin was not accepted
- all others were
- except `undefined` that is _same host_
This PR fixes the origin checking logic so that it actually works.
In addition this PR adds special handling for the Admin UI origin: the origin that the security configuration form that is used to set CORS origin field to non empty value is automatically added to the list of allowed CORS origins. Otherwise Admin UI …

fix: CORS: security routes and origin handling

---

.github/workflows/build-docker.yml
docker/Dockerfile
docker/startup.sh
src/config/config.ts

Build all the server related js code only once and store them as
artifacts. Modify the server's dependencies by removing workspaces
configuration and using npm i from each tarball to update the versions
to point to the tarballs.
Then in reach platform specific Docker build use the prebuilt server
and the modules from artifacts.
This PR also changes the master build to be more in line with the
release build so that the server is installed globally with -g.
Inspired by #1499

chore: optimise Docker master build

---

src/put.js
src/requestResponse.js
test/put.js

fix: missing statusCode when updating meta over WebSocket with put message

---

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js

---
Resolves: https://github.com/SignalK/signalk-server/issues/1425
This request to include this field for N2K was originally for Yacht Devices, and a fix was merged in here: https://github.com/SignalK/signalk-server/pull/1443 This resolved an overlapping issue: https://github.com/SignalK/signalk-server/issues/1442
NavLink2 is also TCP, and this PR adds the no data timeout setting for this, as well.  I'm not sure if there's a reason it wasn't added initially, so feel free to reject this if there's a reason it was left off.  Either way, I think this closes https://github.com/SignalK/signalk-server/issues/1425.

fix: UI: allow configuration of no-data timeout for all TCP N2K sources

---

packages/server-api/src/deltas.ts
packages/server-api/src/index.ts
src/@types/signalk_signalk-schema.d.ts
src/api/course/index.ts
src/api/resources/index.ts
src/app.ts
src/deltaPriority.ts
src/deltacache.ts
src/deltachain.ts
src/index.ts
src/interfaces/plugins.ts
src/serialports.ts
src/subscriptionmanager.ts
src/types.ts

- Move base Signal K types to server-api so that both server and ts plugins can use them
- Move ServerAPI to server-api module (fixes #1516)

Server-api improvements, support plugin development in TypeScript

---

SERVERPLUGINS.md
src/api/apps/openApi.ts
src/api/course/openApi.ts
src/api/discovery/openApi.ts
src/api/notifications/openApi.ts
src/api/resources/openApi.ts
src/api/security/openApi.ts
src/api/swagger.ts
src/index.ts
src/interfaces/plugins.ts
src/serverroutes.ts
test/plugin-test-config/node_modules/testplugin/index.js
test/plugin-test-config/node_modules/testplugin/openApi.json

Allow plugins to expose OpenApi descriptions by implementing getOpenApi method. The description will be included in the server's OpenApi UI apis list.

feature: support openApi in plugins

---

packages/server-admin-ui/src/components/Sidebar/Sidebar.js
src/serverroutes.ts

Since the OpenApi ui is not authenticated and we'd like
it to be available for perusal at demo.signalk.org move
it under a top level menu Documentation that is always
available. We can also add other documentation here in
the future.
OpenApi link need not look different from other many items, make external links look the same as internal.

feature: make OpenApi link always available in the menu

---

src/api/course/index.ts
src/api/course/openApi.json
test/course.ts

Removed references to `waypoints` in `ActiveRoute` as these references are not used.
Waypoint information is available in the referenced route resource.

fix: Remove unused Course OpenAPI schema definitions.

---

src/api/resources/openApi.json
test/resources.ts

Add defintion for route point metadata within the feature `properties` to hold attributes for the points within the route.
This is useful when importing routes from GPX files, etc to hold information such as point name & description.
_Example:_
```
{
"name": "my Route",
....
"feature": {
....
"geometry": {
"type": "LineString",
"coordinates": [
[24.897849923663273, 60.15202408867182], ... , [24.758341055158922, 59.44208867188729]
]
},
"properties": {
"points": [
{"name": "RtePt001"}, ... , {"name": "RtePt005"}
]
}
}
```

feature: Add Route Point Metadata definition to Resources OpenAPI

---

SERVERPLUGINS.md
src/api/swagger.ts

Currently when a plugin provides an openApi.json document, the swagger documentation defines the following `servers`:
- `https://demo.signalk.org${apiDocPath}`
- `${process.env.PROTOCOL ? 'https' : req.protocol}://${req.get(
'Host'
)}${apiDocPath}`
regardless of the `servers` attribute contained within `openApi.json`.
This PR changes the behaviour to only set `servers` to the the urls above when the plugin's `openApi.json` does NOT define a value.
_Plugin **openApi.json** defines value for `servers`:_
_Plugin **openApi.json** DOES NOT define value for `servers`:_

fix: Use servers array in plugin openApi.json.

---

package.json
packages/streams/package.json
packages/streams/serialport.js
src/serialports.ts

The serialport library being used was using 9.0.1, which is no longer maintained. Upgrading to version 11 allows users installing signalk-server on node-18 to use the prebuilt binaries.

chore: upgrade the serialport library to use version 11.0.0

---

packages/server-admin-ui/package.json
packages/server-admin-ui/src/views/security/EnableSecurity.js
packages/server-admin-ui/src/views/security/Login.js
packages/server-admin-ui/src/views/security/Register.js

- Fixed the layout of the prepended fields for Login, EnableSecurity and Register
- Added possibility to press enter to submit the form in the Login and EnableSecurity views

fix: style security related input fields properly, enable enter

---

packages/server-admin-ui/src/actions.js

Instead of showing a stringified version of the json response, we show the message instead.

Fix: Error message when logging in is shown properly

---

packages/server-admin-ui/src/actions.js

When you are not logged in, several api-endpoints return the message "You do not have permission to view this resource, <a href='/admin/#/login'>Please Login</a>" which results in an uncaught error because it can't be parsed to JSON.
This PR resolves this issue by checking the status (and using await/async syntax for cleaner code)

Fix: Resolve uncaught errors when not logged in

---

packages/streams/gpsd.js
packages/streams/package.json

from node-gpsd - this is done to make signalk able to reconnect to gpsd socket when no data has been received for a configurable time.
Tested on my laptop with an ssh port forward to gpsd on my boat -- reconnects fine.
Fixes #1363

Gpsd client package to node-gpsd-client, add reconnect

---

bin/signalk-server
package.json

Feature: minimum version check

---

README.md
src/interfaces/mfd_webapp.ts

Add env variable MFD_ADDRESS_SCRIPT to allow overriding the default MFD advertisement addresses with a shell script that outputs a comma delimited list of addresses to advertise.

feature: override for MFD addresses

---

packages/server-admin-ui/src/views/security/Settings.js
src/tokensecurity.js

Security Settings says 'login session timeout', which is misleading:
if you don't check Remember Me login session has no timeout and
is alive for browser session duration. The value is used to set
maxAge of session cookie when RememberMe is checked.
The current default value of 1d for Remember Me timeout is not
very intuitive: without RememberMe checked the login lasts for
the browser session, which often is much longer than 1d. With
the default 1d and Remember Me checked your login session will
timeout in 1d, when you probably wanted that the server would
remember you over browser restarts for quite a bit longer.
This changes the default value to 3 months, trying to strike
a balance between security (eventual timeout) and convenience
(the server actually remembering you over browser …

feature: Remember Me improvements

---

src/index.ts

Reduce the notification state severity to normal.
There being a new version available is a pretty low severity notification. Just the fact that there is a notification for is probably enough.
See also https://github.com/SignalK/instrumentpanel/issues/245

feature: newServer notification as normal

---

packages/server-admin-ui/src/views/Dashboard/Dashboard.js
packages/streams/serialport.js
packages/streams/simple.js
packages/streams/tcp.js
src/app.ts
src/deltastats.ts
src/index.ts

Add new icon to indicate outbound traffic on Connections.
Change the previous feed icon to 'login' to indicate incoming traffic so that we can use the 'logout' icon for outbound traffic.

feature: add write statistics to dashboard

---

src/api/resources/index.ts

Added additional checks for identifying provider when using `setResource()`.
Fixes issue where creating a new resource entry was failing.
Fixes #1600

Fix: Issue when creating resources via plugin interface

---

packages/server-admin-ui/src/views/security/Settings.js
src/cors.ts

Fix: CORS logging issue #1576

---

packages/server-admin-ui/src/views/Configuration/Configuration.js
packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js
packages/server-admin-ui/src/views/ServerConfig/ProvidersConfiguration.js
packages/server-admin-ui/src/views/ServerConfig/Settings.js
packages/streams/logging.js
src/config/config.ts
src/serverroutes.ts

Occasionally people have trouble with data log files filling
their storage. This changes the default from keeping the data log
files forever to keeping only 24 last hourly log files.
In addition the terminology in the Admin UI is changed to talk about 'Data Logging'.

Keep only recent data log files by default

---

packages/server-admin-ui/scss/_custom.scss
packages/server-admin-ui/src/views/Configuration/Configuration.js

Feature: indicate clearly that a plugin needs configuration

---

packages/streams/canboatjs.js
src/deltacache.ts
src/streambundle.js

See the commit messages for individual optimizations. Each of these improved measurably the throughput of the server that was replaying n2k data repeatedled. Less string splits mean also less temporary memory allocations.

refactor: minor optimisations

---

packages/server-api/src/coursetypes.ts
src/api/course/index.ts

Restructure the course types to have distinct types instead of a single PointDestination with all properties optional, that does not really document the structure of the different input types.
Drop PointDestination.type, as it was not used anywhere.
Instead add CoursePointType to be used as the CourseInfo nextPoint/previousPoint type discriminator.

refactor: course types fiddling

---

packages/server-api/src/coursetypes.ts
packages/server-api/src/index.ts
src/api/course/index.ts
src/api/index.ts
src/interfaces/plugins.ts

Create an interface for the Course API to expose to plugins to enable them to interact with the Course API.
The functions accept parameters and return values of the same type as the equivalent REST API function.
Functions include: 
- `getCourse()`: retrieve current course details
- `setCourse()`: Set position / waypoint as current destination
- `setRoute()`: Follow a route.
_Note: `server-api` types have been updated as part of this PR and will require a new version to be published when this is merged_

feature: Expose a Course API interface to plugins.

---

packages/server-api/src/index.ts
src/deltastats.ts
src/interfaces/plugins.ts

Add a way for plugins to report that they are handling outgoing (out = from the server to the outside world) traffic to update the output rate & icon on the dashboard.

feature: add reportOutputMessages to server plugin API

---

packages/server-admin-ui/src/views/security/Settings.js
src/cors.ts

- Fixes #1640 : #1581 accidentally disabled the default CORS behavior, that allows all CORS origins with `Access-Control-Allow-Origin: *`
- fix: do not add `localhost` addresses to the CORS origins when saved from the Admin UI
- feature: add a new special `*` value for allowed CORS origins. This will allow all origins and echo back the origin in `Access-Control-Allow-Origin` instead of the default *. This allows configuring the server to work with security enabled and `credentials:include` requests from all origins

fix: default cors, add * as an allow-all configuration, don't add localhost to allowed cors hosts

---

.github/workflows/test.yml

In preparation for phasing out 16 and eventual adoption of 20 let's run tests with all these versions for now.

chore: run tests with node 16,18 and 20

---

src/interfaces/plugins.ts

Loading the configuration form for a plugin with no schema would crash the configuration ui and the browser would persist the configuration ui state so that subsequent attempts to navigate to plugin configuration would try to open the problematic plugin's configuration, again resulting in a ui crash.
Change the server to always provide an empty schema in case the plugin is not defining one and log an error message about it when the plugin configuration page is loaded.

fix: guard against missing plugin schema

---

packages/streams/autodetect.js

If the original delta data has timestamps use them, otherwise use the timestamp of the multiplexed data also in deltas instead of letting the server fill in the current time.
Fixes #1659.

fix: use multiplexed file timestamps in deltas

---

packages/streams/autodetect.js

Logged output from plugins has the plugin id in the
discriminator field instead of the one letter data type
discriminator. If the first line of the multiplexed file
is from a plugin the file type detection does not work
and the file fails to play back silently.
Assert the minimum number of ; delimiters to be 3
instead of checking that charAt(15) is ;.
If a multiplexed file line contains ; in the data, which is
perfectly possible for delta JSON, the part of the data
after ; would get thrown away.
Fix by joining the back with ; as delimiter.

Fix: multiplexed file detection & semicolon handling

---

packages/server-admin-ui/src/views/Webapps/Embedded.js
packages/streams/canboatjs.js
src/events.ts
src/index.ts
src/interfaces/plugins.ts
src/interfaces/ws.js
src/pipedproviders.ts
src/security.ts
src/serverroutes.ts

feature: refactor Events handling
- Add the ability to 'subscribe' to events on the server
with a comma delimited list of events in the events
query parameter of the WebSocket connection url
- Add a safe way to emit server events: dispatching
events to listeners is inside try..catch so that
a listener throwing will not disturb other listeners. Logic
copied from https://github.com/MetaMask/safe-event-emitter/blob/main/index.ts
Fixes #1467.
- Add emitWithEmitterId that allows gathering stats about
emitters and their event flow
- add server api /skServer/eventsRoutingData to expose statistics as well
as events routing data event emitters and listeners
- add event canboatjs:unparsed:data to provide access to n2k data that
canboatjs can not parse
- add events canboatjs:error and …

Event handling improvements: events over WebSocket, endpoint for events routing data, event dispatch error handling

---

src/tokensecurity.js

Let's assume that the user's intention when checking Remember Me in the login form is that they don't want their login to expire, ever.
This changes the default for the remember me expire to be NEVER.

feature: rememberme expires to NEVER

---

packages/server-admin-ui/src/views/Configuration/Configuration.js

Remove the annoying scroll-to-top that was happening when toggling the plugin's enabled, data logging and debug settings.

fix: remove scroll when toggling plugin

---

packages/server-admin-ui/src/components/Sidebar/Sidebar.js
packages/server-admin-ui/src/views/ServerConfig/Logging.js
packages/server-admin-ui/src/views/ServerConfig/ServerLog.js

Replace debug text field & the individual debug key switches with a multiselect.
Rearrange & reword the debug settings persist and log window pause switches.
Move Data log files under Server Logs (that is renamed to plural).

feature: improve Server log & data log files UI

---

packages/server-admin-ui/src/views/Dashboard/Dashboard.js

This PR introduces changes to `Connection activity` view on SK Admin UI.
Currently activity view is mixed list of `Connections` and `Plugins` activities and list is not sorted at all.
Update will split activities to `Connections` and `Plugins` and sort list in alphabetic order.
Example view:

SK Server Admin UI Activity View Update

---

src/tokensecurity.js

NEVER was previously supported only for access request tokens, this adds support for it in regular tokens so that #1670 actually works.

fix: support for NEVER in RememberMe expires

---

src/api/resources/index.ts

As requests for chart tiles do not return a JSON response, they will be passed through to the `chart provider` by calling next().
Chart provider should ensure it has a handler for requests to: `/signalk/v2/api/resources/charts/(\\w*\\W*)+/[0-9]*/[0-9]*/[0-9]*`

Fix: Resources API - Handle requests to GET  chart tiles.

---

src/interfaces/plugins.ts
test/plugins.js

- `registerWithRouter()` now runs during plugin startup not before. If the plugin was never started during a server session, requests to it's endpoints will result in a `404` response.
- Added a middleware to check if the plugin is running by checking if it has active `onStopHandlers`. If the plugin is not running any requests to it gets a `500` response
- This change was added because the [Docs](https://github.com/SignalK/signalk-server/blob/master/docs/src/develop/plugins/server_plugin_api.md) state that:  
> It should be noted that Express does not have a public API for deregistering subrouters, so stop does not do anything to the router.
This is now a way to notify any users of the plugin once it has stopped. Before you could make request to the endpoints of a plugin even after it …

Fix: disabled plugins no longer have an active API interface

---

src/interfaces/plugins.ts
test/plugins.js

Revert "Fix: disabled plugins no longer have an active API interface (#1684)"
This reverts commit c119539e5031fd082ca9b61eb6d6229b07622014.

Fix: revert plugin API change that broke plugin configuration saving

---

.github/workflows/build-base-image.yml

Base image build is chained with validation step, which verify that base image is valid and SK docker release images can be build based on it successfully.

fix: test baseimage docker after build by building SK release docker image without pushing it to registry

---

packages/resources-provider-plugin/CHANGELOG.md
packages/resources-provider-plugin/README.md
packages/resources-provider-plugin/package.json

Update resources-provider plugin package keyword to `signalk-category-utility` so it is listed correctly in AppStore.

chore: Resources - update plugin catagory keyword

---

packages/server-admin-ui/src/views/appstore/Apps/Apps.js
packages/server-admin-ui/src/views/appstore/AppsList.js
packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/NameCellRenderer.js
src/interfaces/appstore.js

- sort apps list newest first, show publish date of the latest version in the list
- misc small fixes

Appstore fixes

---

src/modules.ts

The secondary npm registry we have been using seems to have disappeared, so remove it so that it does not cause extra 20s delay.

fix: remove api.npms.io

---

src/interfaces/ws.js

Fixes #1717.
Reduce memory consumption of string values used in tracking what metadata we have sent for a ws connection by keeping a cache of shared string values for this. This will deduplicate the values and help with memory consumption with a large number of AIS targets and multiple ws connections.
The cache is purged every 30 minutes to get rid of data for AIS targets that have disappeared.

fix: reduce ws meta tracking memory consumption

---

docs/src/installation/command_line.md
src/interfaces/ws.js

Fixes https://github.com/SignalK/signalk-server/issues/1718
Do not immediately hand ws up if the max send buffer size is exceeded, but start monitoring for MAXSENDBUFFERCHECKTIME milliseconds. If the buffer remains above the threshold all the time terminate the connection. If the buffer has dropped below the threshold during subsequent writes to the ws connection the timer is reset.

fix: check ws max send buffer size over time

---

packages/server-admin-ui/src/views/appstore/Apps/Apps.js
packages/server-admin-ui/src/views/appstore/AppsList.js
packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/ActionCellRenderer.js
packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/NameCellRenderer.js
packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/VersionCellRenderer.js
packages/server-admin-ui/src/views/appstore/appStore.scss

Created a dedicated column version on the appstore page. This aims at resolving the confusion from user while browsing for plugins. 
Few users complained about the version number being detrimental to plugin search.
Also improved the responsivity of the search bar on mobile version. 
NOTE: I also removed the last updated date as it is not working well with the new column. Maybe we should display that information with a tooltip or differently.

Appstore UI/column version

---

src/security.ts
src/tokensecurity.js
test/security.js
test/servertestutilities.js

This commit updates the security code to allow for users to be configured in `security.json` without a password value. These users can then only be logged in with using the `signalk-generate-token` script.
Fixes https://github.com/SignalK/signalk-server/issues/1714.

feat: Allow for users without password

---

src/interfaces/playground.js
src/interfaces/ws.js
src/put.js
test/delete.js
test/ts-servertestutilities.ts

There is one issue... When there is the same meta data from baseDeltas and from another source (like a plugin). This will delete the plugins meta for that field until restart or the plugin sends it again.
I think we can live with that...?

feature: add support to DELETE meta data

---

packages/server-admin-ui/src/views/DataBrowser/Meta.js
src/put.js
src/zones.ts

This changes the behavior of saving metadata so that an empty zones array resulting from removing the last, previously added zone, will be handled as null value. The code handling full model deals properly with nulls, while empty arrays are silently ignored as updates.

fix: removing last zone was not reflected in full data

---

packages/server-admin-ui/src/components/Sidebar/Sidebar.js

Fixes #1752.
Not perfect, because the > is over the badge, but maybe good enough.

feature: show accessRequests in Security menu

---

src/api/swagger.ts
src/interfaces/applicationData.js
src/interfaces/appstore.js
src/interfaces/logfiles.js
src/interfaces/plugins.ts
src/interfaces/providers.js
src/serverroutes.ts
src/tokensecurity.js
test/httpprovider.js

Replace plain res.send calls that set mime type to text/html with res.json or set mime type explicitly to text/plain so that there is less chance of injecting html content.

fix: plain res.send calls

---

src/serverroutes.ts

The endpoint was using GET and unused, so let's remove it.

chore: remove unused token generation endpoint

---

src/interfaces/logfiles.js

The logfiles endpoint was missing admin authentication and allowed directory traversal.

fix: logfiles directory traversal and authentication

---

src/interfaces/plugins.ts

Adds "supportsPut: true" meta for any paths that support put. Allows clients to detect and list these.
(Needed for Wilhelm SK Shortcut/Siri integration)

feature: add supportsPut meta data to paths that have put handlers

---

packages/resources-provider-plugin/src/index.ts
src/api/resources/index.ts

The `setResource()` and `deleteResource()` interface functions exposed by Resources API to plugins does not trigger the sending of a delta to notify clients that a resource change had occurred.
This PR updates these functions to send a delta when the operation is successful.
This now aligns with the behaviour when using the API HTTP endpoints.

fix: Resources API - Send delta message when resources are added / deleted via the plugin interface.

---

docs/src/develop/plugins/server_plugin_api.md

Remove reference in documentation to the `notify()` function which is part of #1560 the proposed Notification API.

doc: Remove reference to non-implented `notify()` function

---

packages/server-api/src/deltas.test.ts
packages/server-api/src/deltas.ts
packages/server-api/tsconfig.json

Fix delta types that are not in line with the specification.
Do not include test files in the declaration.

Fix: server api types

---

docs/src/develop/plugins/server_plugin.md
src/interfaces/plugins.ts

Fixes #1802
Add support for plugins returning a Promise from their stop implementation to allow async stop operations. In plugin restarts, mainly when changing configuration, we wait for the optional stop Promise to resolve before calling plugin.start().

feature: support async plugin.stop implementation

---

package.json

v0.4.34 doesn't have multi-arch images, so for those of us running on arm boxes (such as, for instance, lima on a new Mac) - running build:doc doesn't so much work. The latest mdbook release, v.0.4.40 seems to build things just fine and has multi-arch images, so update the pin.

Update mdbook version for multiarch support

---

src/api/resources/openApi.json

Updated OpenAPI definition for Charts to include:
1. Add PUT / POST / DELETE operation definitions for `chart` resources.
2. S-57, mapboxstyle chart types
3. Chart `identifier` is optional ((as per specification)

update: Resources API OpenAPI definition for charts

---

packages/resources-provider-plugin/package.json

Add `@signalk/server-api` as a dependency rather than a dev-dependency.
This fix is included as part of v1.2.1 release.

fix: resource-provider server-api dependency

---

docs/src/develop/webapps.md
src/tokensecurity.js

Webapps are often used in multiple windows and the browser's login status in session cookie may change in another window or in another webapp (Admin UI vs Freeboard, Kip etc). The regular session cookie is set to be httpOnly, so it is not available for clientside code.
This adds a separate cookie that is set and removed by the server when the user's login status changes. A webapp can poll for changes of this cookie to react. One notable use case for this is applicationData that is available only when the user/browser is logged in.

feature: add client side cookie to expose login info

---

docs/src/develop/webapps.md
src/serverroutes.ts

Signal K webapps have displayName property. This PR adds automatic redirect to that webapp when the server's root is accessed with a hostname whose first element is the webapp's displayName.
So if you have a webapp whose displayName is foo and you access the server using url like http://foo.bar.org:3000/ you will be redirected to that webapp instead of the default landingPage that is the Admin webapp.

feature: redirect to webapp by displayName

---

docs/src/develop/rest-api/course_api.md
packages/server-admin-ui/src/views/ServerConfig/Settings.js
packages/server-api/src/deltas.ts
src/api/course/index.ts
src/api/course/openApi.json
src/config/config.ts
src/serverroutes.ts
test/ts-servertestutilities.ts

Provide the ability for the Course API to set the destination based on the data received from NMEA connections. This allows application developers to use V2 Course API with course data coming from NMEA 0183 and NMEA 2000 sources.
Delta messages with a _source.type_ of NMEA0183 or NMEA2000 containing path values for
- `navigation.courseRhumbline.nextPoint.position` OR 
- `navigation.courseGreatCircle.nextPoint.position` 
will trigger invoke the course `setDestination()` method.
The following priorities are applied when determining whether a destination will be set from an NMEA delta:
1. Destination requests via Course API endpoints have the highest priority and will ALWAYS be actioned!
2. If a destination is set, only updates from the same source are actioned (unless it is an API request) …

feature: Add NMEA stream handling to Course API.

---

src/config/config.ts
src/serverroutes.ts

Fixes https://github.com/SignalK/n2k-signalk/issues/277

fix: communication.callsignVhf not set properly in baseDeltas.json

---

src/api/course/index.ts

Add more rigorous validity test when setting `nextPoint.position` as some stream sources may supply invalid data values
e.g. `{latitude: null, longitude: null}`

Fix: Course API - Update test for valid destination point value

---

src/api/course/index.ts

Use the improved position validity test (#1840) to determine when to clear `course.nextPoint.position` value.
Ensures the same validity test is used for both setting and clearing destination position.

Fix: Clear destination on empty or invalid position received via NMEA

---

.gitignore
packages/streams/n2kAnalyzer.js

- fix analyzerOutEvent event name so that raw analyzer output is emitted correctly when using canboat
- output canboat version in server log on startup
- ignore IDEA project file
- fix accidental global variable

fix: canboat analyzerOutEvent event name & minor fixes

---

.github/workflows/release.yml

Warnings from action:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: mikepenz/release-changelog-builder-action@v1, actions/create-release@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Upgrade Signal K release action

---

docs/src/develop/rest-api/resources_api.md
src/api/resources/openApi.json

Update the Resources API OpenAPI definition to support a zoom query parameter to allow a zoom level to be provided in a resource request.
Zoom levels equate to the resolution in the following document: https://wiki.openstreetmap.org/wiki/Zoom_levels
Example requests:
`GET ./signalk/v2/api/resources/notes?zoom=9`
`GET ./signalk/v2/api/resources/notes?position=[5.562490300291487,53.01296548279345]&distance=92000&zoom=9`
Ref: #1851

Feature: Add zoom query parameter to Resources OpenAPI definition

---

.github/workflows/release.yml

Release docker image will be tagged
- v2.12.0 (full version)
- v2 (major version)
- latest

chore: docker release image versions with full, major and latest tags

---

.github/workflows/release.yml

Docker meta is using `id: docker_meta` while `tags: ${{ steps.meta.outputs.tags }}`
Corrected to `tags: ${{ steps.docker_meta.outputs.tags }}`

fix: docker build tag variable name corrected

---

docker/Dockerfile_base_test

Node-gyp failing to install needed modules without python3-pip. Same time added python3-env.

fix: python3-pip added for node-gyp

---

packages/streams/gpiod-seatalk.js

This fixes issue #1865 
I tested this on an OpenPlotter image with no ST1 source at hand.
@sailoog may want to verify that I didn't break anything.

fix: Seatalk1 gpiod breaks if default value of GPIO pin isn't changed

---

packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js
src/interfaces/providers.js

**fix:**
```
if (
provider.options.type === 'canbus-canboatjs' &&
!provider.options.uniqueNumber
) {
provider.options.uniqueNumber = Math.floor(Math.random() * 2097151)
}
```
this statement never set`provider.options.uniqueNumber` as if not assigned `!provider.options.uniqueNumber` always evaluates to `false`
**feature:**
introducing new input parameter for `canbus-canboatjs` input provider, adding UI setup fields and comments to set. By default it follow current logic.
background for this feature:
B&G MFD displays (eg Triton2) can display information from different NMEA2000 sources. For example to display GPS coordinates need to go to setup menu, select Sources, Navigation position and then select which NMEA2000 device we want to use as a source (SignalK server, Garmin GPS 24xd or any …

feature: introducing optional canbus Mfg code, fixing canbus provider UniqueNumber logic

---

src/modules.ts

When the user clicks the Update button the App store UI is not showing that the server is doing the update IF there is an error response from the npm registry when fetching the list of plugins & webapps.
Npm registry has rate limits and apparently some people have hit those: in the course of using the App store ui the server fetches the lists of modules and webapps several times, that can cause npm registry to return an error message instead of the listing.
This PR fixes the UI not updating with two separate methods:
- if npm registry returns an error the error is not simply ignored, but handled like the App store would not be available
- by adding a 1 minute cache for the npm registry modules listing
The cache should keep the rate limit not intervening and the App store working properly.

fix: app store ui not updating to show installing plugins; cache npm response for one minute

---

src/modules.ts

It seems npmjs no longer provides the author information from the module's original package.json. Instead let's use the publisher's username in npmjs instead, as that seems to be there consistently.

fix: author in Appstore

---

src/api/course/index.ts

This is what I meant: we just test for either isValidRouteCourse or isValidWaypointCourse, otherwise return explicitly the "no route value". To me this is much more understandable than the pretty complex boolean logic.
This also simplifies things so that instead of code like `if (condition) { return true} else { return false }` we simply `return condition` (and make sure condition is boolean and not `boolean | undefined`).
Hopefully I did not break anything in the refactor...

Simplify logic

---

src/modules.ts

Npm search api windows the results to max 250 results, so keep fetching repeatedly until we have retrieved all search results.
Fixes #1881.

fix: npm search api window hiding some plugins

---

src/api/course/index.ts

Addresses #1873 
Perform check on resource references (`href`) when loading stored state to ensure the resources still exist.

Fix: Course API - check loaded state href values more rigorously

---

packages/streams/autodetect.js

Encountered a multiplexed log file with empty line in the beginning. Fix by skipping empty lines until we see a line that we can recognize.

fix: multiplexed playback with empty lines

---

.github/workflows/build-docker.yml
.github/workflows/release.yml

Signal K docker images pipelines:
- release pipeline
- development pipeline
Upgrades:
- amd64 (ubuntu-latest) and arm64 (ubuntu-24.04-arm) virtual machines to enhance build speed (no more qemu)
- parallel build processes for each images
- Ubuntu 22.04 and 24.04 OS bases
- housekeeping process to clean up repositories (ghcr.io & docker hub) from untagged and temporary build images files

chore: SK docker images build pipelines upgrades

---

.github/workflows/build-docker.yml

Dev docker build fails if two or more commits were added while docker build was going on. This fix it by adding dynamic tag ending.

fix: change temp docker images static tag ending to per build

---

.github/workflows/release.yml

Fixes release docker build to include modified `Dockerfile_rel`.
Support concurrent docker builds with unique, per build temp image tag, same fix as for dev docker.

 fix: release docker build process fix and improvements

---

.github/workflows/release.yml

Fly.io deployment will run too early and caused build failure.
Minor fix for 24.04 tag.

fix: fly.io deployment job order change and tag fix

---

packages/resources-provider-plugin/package.json

I was trying to get to the code from npmjs.com and it links to a repository that doesn't exist.

docs: Update repository link on resources-provider plugin

---

src/modules.ts

I noticed that the AppStore is making requests to `http` instead of `https`.  npmjs.org redirects all requests to https, so this removes an extra request.
```
$ curl -I http://registry.npmjs.org/-/v1/search\?text\=signalk
HTTP/1.1 301 Moved Permanently
Date: Thu, 20 Mar 2025 20:21:02 GMT
Content-Type: text/plain;charset=UTF-8
Connection: keep-alive
Location: https://registry.npmjs.org/-/v1/search?text=signalk
Set-Cookie: _cfuvid=aV51wGwtAGUgO1T7zwNPoHtMwfDQWFLWI0B77b1TLms-1742502062613-0.0.1.1-604800000; path=/; domain=.npmjs.org; HttpOnly
Server: cloudflare
CF-RAY: 9237e9e33ef6dab9-MIA
```

fix: Use https for NPM request to avoid redirect

---

packages/server-api/tsconfig.json

This sets the `include` path in the tsconfig.json for the server-api. Otherwise it tries to compile files `dist` and fails with a warning.
```
❯ npm run build
> signalk-server@2.13.5 build
> tsc --build && npm run build:docs
error TS5055: Cannot write file '/Users/bkeepers/projects/signalk/signalk-server/packages/server-api/dist/autopilotapi.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '/Users/bkeepers/projects/signalk/signalk-server/packages/server-api/dist/autopilotapi.guard.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '/Users/bkeepers/projects/signalk/signalk-server/packages/server-api/dist/coursetypes.d.ts' because it would overwrite input file.
error TS5055: Cannot write file …
```

chore: fix error when running `npm run build` in development

---

packages/server-admin-ui/scss/core/_grid.scss
packages/server-admin-ui/src/views/appstore/Apps/Apps.js
packages/server-admin-ui/src/views/appstore/appStore.scss

This is a small fix to the Admin UI to make the padding consistent between pages and states. Previously the App Store had its own top padding and extra horizontal padding, and none of the other pages had top padding.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td><img width="1178" alt="image" src="https://github.com/user-attachments/assets/c458c59a-b983-4e93-bf33-726cd827c489" /></td>
<td><img width="1180" alt="image" src="https://github.com/user-attachments/assets/5d8d0eb9-b820-4797-9f38-4fd2ac0364ac" /></td>
</tr>
<tr>
<td>
</td>
<td><img width="1181" alt="image" src="https://github.com/user-attachments/assets/cb423b07-278f-4b0e-b52b-71a133cc6d99" /></td>
<td>
</tr>
<tr>
<td><img width="1180" alt="image" src="https://github.com/user-attachments/assets/9fbaf328-221c-458a-93b4- …

fix: Make padding consistent in Admin UI

---

README.md
docs/src/develop/contributing.md

I didn't see any docs on how to run the server in development, and it took me a bit to figure out I had to run `npm run build:all` and not just `build`. So this documents how to get the server running in development.
Also, it seems there isn't any form of hot reload or development server setup, is that right? Would you be open to a pull request that switches to something like [Vite](https://vite.dev) that supports hot module reloading and typescript natively?

doc: how to run the server for development & consolidate contributor docs

---

src/interfaces/plugins.ts

The link in the deprecated `setProviderStatus`/`setProviderError` messages is broken, so this updates the message to explictly say what to use instead. It also switches to using the `deprecate` function from node's `util` module to do the deprecation, which support showing a stack trace.
Run `NODE_OPTIONS='--trace-deprecation' signalk-server` to see a full stack trace.
```
(node:76180) DeprecationWarning: setProviderStatus() is deprecated, use setPluginStatus() instead
at plugin.start (/Users/bkeepers/projects/signalk/signalk-tides-api/src/index.js:68:9)
at doPluginStart (/Users/bkeepers/projects/signalk/signalk-server/lib/interfaces/plugins.js:312:20)
at doRegisterPlugin (/Users/bkeepers/projects/signalk/signalk-server/lib/interfaces/plugins.js:480:13)
at registerPlugin …
```

doc: Fix broken link in plugin deprecation warning

---

docker/Dockerfile_base_22.04
docker/Dockerfile_base_24.04

Dockerfile_base_22.04 & Dockerfile_base_24.04:
- Added chmod u+s /usr/bin/date. No need to use `sudo` to set time.
- Cleaned up apt cache and temporary files.
Dockerfile_base_22.04:
-  Added installation of python3-venv and python3-pip.

chore: base Dockerfile updates

---

packages/server-admin-ui/src/views/DataBrowser/DataBrowser.js

This fixes the usage of react-json-tree after the update to 0.20.0 in #1925. The latest version changes the import and uses a dark theme by default.
@tkurki Opening this a separate PR since I don't have access to push to the original PR. Let me know if prefer a different workflow.

chore: fix react-json-tree usage after update

---

.github/workflows/build-docker.yml
.npmignore

[This workflow](https://github.com/SignalK/signalk-server/actions/runs/14300603875/job/40074310389#step:4:1153) is failing after #1914 because it can't find the `typedoc-signalk-theme` package. The workflow creates local packs of the modules in `packages/` and then [clears out the `workspaces` config from `package.json`](https://github.com/SignalK/signalk-server/blob/1785734d9438a490782dccf00664f7e00d455feb/.github/workflows/build-docker.yml#L39). This updates the action to make local packs for all `packages/*`, and then just deletes the `typedoc-signalk-theme` package, which is only a devDependency.
I also noticed that several of the `*.tgz` files were ending up in the final `signalk-server` package, so I updated the npm ignore config.

chore: fix docker dev build (typedoc-signalk-theme)

---

.github/workflows/build-docker.yml
docker/Dockerfile
docker/README.md

It took me a minute to figure out how to build the docker image locally from source, so I added some brief docs for it.
This also updates the docker file to use [docker build variables](https://docs.docker.com/build/building/variables/) instead of running `sed` during the build process.
Lastly, this also fixes these warnings I was getting when building the images:
```sh
$ docker --version
Docker version 27.4.0, build bde2b89
$ docker build -t signalk-server:master -f docker/Dockerfile .
...
3 warnings found (use docker --debug to expand):
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 41)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 42)
- JSONArgsRecommended: JSON arguments …
```

docker: document local build, refactor & improve build

---

packages/server-api/src/serverapi.ts
src/deltachain.ts
src/index.ts
src/interfaces/plugins.ts
src/streambundle.ts

This fixes an [error reported](https://discord.com/channels/1170433917761892493/1360533803533340704/1361802762987372614) by @KEGustafsson introduced in #1918. I have not been able to recreate it, but apparently there are instances where `update.values` is present, but is not an array. Looking back at #1918, it looks like the old code [did have an `if` conditional](https://github.com/SignalK/signalk-server/pull/1918/files#diff-fb03df6f129b4ff2d3608e512e7ca174c9d92d6fe93307c984c730b45903889bL38), so there must be instances where it is `null`/`undefined`. ~~I updated the types to be consistent with the implementation as well.~~
While I was looking at that, I noticed that `app` is injected into stream bundle, but is unused, so I removed it in another commit.

fix: fix streambundle error after port to TypeScript

---

Procfile
bin/log2sk
bin/signalk-generate-token
bin/signalk-server
bin/signalk-server-setup
package.json
tsconfig.base.json

This adds the [--enable-source-maps](https://nodejs.org/dist/latest-v12.x/docs/api/cli.html#cli_enable_source_maps) to node invocations, which will show real source locations for errors in the server, and any plugin that includes source maps.
Here's a diff of the stack trace from #1957 with source maps enabled:
```diff
at /Users/bkeepers/projects/signalk/signalk-server/node_modules/debug/src/common.js:100:24
at String.replace (<anonymous>)
at debug (/Users/bkeepers/projects/signalk/signalk-server/node_modules/debug/src/common.js:91:22)
-    at safeEmit (/Users/bkeepers/projects/signalk/signalk-server/dist/events.js:84:17)
-    at emitWithEmitterId (/Users/bkeepers/projects/signalk/signalk-server/dist/events.js:137:9)
-    at Function.emit …
```

feat: enable node source map support

---

packages/server-admin-ui/src/views/DataBrowser/DataBrowser.js

* Combine unit with value in DataBrowser: append the unit to numeric values to make the layout a bit more compact and readable.
* Update timestamp formatting logic to display only the time for same-day timestamps and the full date-time format for others
* Overall table responsiveness improvements: see 9441e783164f2f0ad58421818a849f411dab9c85 for details
* Use React Select in Context menu to allow searching and include context name.

Databrowser layout & responsiveness improvements

---

.github/workflows/build-docker.yml
package.json
packages/typedoc-theme/package.json
typedoc.json

In preparation for publishing it so that it is
a proper, installable module and not just a
ghost move the module under @signalk organisation.

chore: @signalk/typedoc-signalk-theme

---

.github/workflows/build-docker.yml

It seems that getting Docker builds to work in PRs requires a nontrivial amount of work. PRs breaking docker build have not been a frequent problem,  so let's revert these.

Revert docker pr builds

---

test/deltaPriority.ts

Import from ts instead of js to avoid
SyntaxError: Named export 'SourcePrioritiesData' not found. The requested module '../dist/deltaPriority.js' is a CommonJS module, which may not support all module.exports as named exports. C

fix: test run on Node v24

---

.github/workflows/build-base-image.yml

Fixes build error with #2078 
Base image on Nodejs 24.x will support arm64 and amd64, not arm/v7
Base image on Nodejs22.x will support amr64, amd64 and arm/v7

fix: nodejs 24.x for arm64 and amd64 not arm/v7

---

src/api/resources/openApi.json

The chart server types defined in the openapi definition are used to validate request payloads.
They do not match the values used in practise by charts-plugin, etc and need to be aligned to allow chart entries to be written via the resources API.

fix: Align chart server type OpenAPI definitions.

---

packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/VersionCellRenderer.js
packages/server-admin-ui/src/views/appstore/appStore.scss

Previously the installed version would show correctly only when there is
an update available. This makes sense for normal versions, because if
there is no update available you are running the latest version.
However, for beta versions there probably is no update yet available, as
you are have a prerelease version.
This comment changes the logic to always show installed version, if that
is available.
Fixes SignalK/freeboard-sk#291

Fix: installed plugin/webapp version display

---

bin/signalk-server-setup

Fixes #1814. On modern systems logging is alredy using journal under the hood, so remove the superfluous
config that does nothing, only generates a warning.

fix: use default systemd logging
